/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:17 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <WebCore/DOMNode.h>

@class NSString, DOMElement, DOMCSSStyleDeclaration;

@interface DOMAttr : DOMNode

@property (copy,readonly) NSString * name; 
@property (readonly) char specified; 
@property (copy) NSString * value; 
@property (readonly) DOMElement * ownerElement; 
@property (readonly) DOMCSSStyleDeclaration * style; 
-(NSString *)name;
-(NSString *)value;
-(void)setValue:(NSString *)arg1 ;
-(DOMCSSStyleDeclaration *)style;
-(char)specified;
-(DOMElement *)ownerElement;
-(char)isId;
@end

