/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:25 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Message.framework/Message
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Message/Message-Structs.h>
@class NSString, NSMutableData;

@interface MFDbJournal : NSObject {

	NSString* _path;
	opaque_pthread_mutex_t _lock;
	int _fd;
	NSMutableData* _buffer;

}
-(void)dealloc;
-(char)flush;
-(void)clear;
-(id)initWithPath:(id)arg1 ;
-(char)append:(const char*)arg1 ;
-(char)mergeWithDatabase:(sqlite3Ref)arg1 ;
-(void)_resetBuffer;
-(char)_processJournalFile:(id)arg1 db:(sqlite3Ref)arg2 ;
@end

