/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:23 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Message.framework/Message
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Message/MFMailMessage.h>

@class MFMessageBody, MFMutableMessageHeaders;

@interface MFOutgoingMessage : MFMailMessage {

	MFMessageBody* _messageBody;
	MFMutableMessageHeaders* _messageHeaders;

}
-(void)dealloc;
-(unsigned)messageSize;
-(id)mutableHeaders;
-(void)setMessageBody:(id)arg1 ;
-(id)messageStore;
-(id)messageBody;
-(id)messageBodyIfAvailable;
-(id)messageData;
-(char)messageData:(id*)arg1 messageSize:(unsigned*)arg2 isComplete:(char*)arg3 downloadIfNecessary:(char)arg4 ;
-(void)setMutableHeaders:(id)arg1 ;
-(id)headersIfAvailable;
-(id)headers;
@end

