/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:11 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol IKAppPlayer;
@class IKJSPlayer, IKAppPlaylistBridge, IKAppMediaItemBridge;

@interface IKAppPlayerBridge : NSObject {

	id<IKAppPlayer> _appPlayer;
	IKJSPlayer* _jsPlayer;
	int _state;

}

@property (nonatomic,readonly) id<IKAppPlayer> appPlayer;                            //@synthesize appPlayer=_appPlayer - In the implementation block
@property (assign,nonatomic,__weak) IKAppPlaylistBridge * playlist; 
@property (nonatomic,__weak,readonly) IKJSPlayer * jsPlayer;                         //@synthesize jsPlayer=_jsPlayer - In the implementation block
@property (nonatomic,readonly) IKAppMediaItemBridge * currentMediaItem; 
@property (nonatomic,readonly) int state;                                            //@synthesize state=_state - In the implementation block
-(void)play;
-(IKAppMediaItemBridge *)currentMediaItem;
-(int)state;
-(void)stop;
-(void)pause;
-(void)stateDidChange:(id)arg1 ;
-(void)scan:(double)arg1 ;
-(void)setElapsedTime:(double)arg1 precise:(char)arg2 ;
-(void)setTimedMetadataKeysToObserve:(id)arg1 ;
-(void)timedMetadataDidChange:(id)arg1 value:(id)arg2 ;
-(id)initWithJSPlayer:(id)arg1 ;
-(id<IKAppPlayer>)appPlayer;
-(IKJSPlayer *)jsPlayer;
-(void)setPlaylist:(IKAppPlaylistBridge *)arg1 ;
-(IKAppPlaylistBridge *)playlist;
@end

