/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ITMLKit/IKJSObject.h>
#import <ITMLKit/IKDOMLSException.h>

@protocol IKDOMLSException <JSExport>
@property (assign,nonatomic) int code; 
@required
-(int)code;
-(void)setCode:(int)arg1;

@end


@interface IKDOMLSException : IKJSObject <IKDOMLSException> {

	int code;

}

@property (assign,nonatomic) int code; 
+(id)exceptionWithAppContext:(id)arg1 code:(int)arg2 ;
-(int)code;
-(void)setCode:(int)arg1 ;
@end

