/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <ITMLKit/ITMLKit-Structs.h>
@class IKDOMNode, IKViewElementStyleComposer, NSMutableDictionary;

@interface IKDOMNodeData : NSObject {

	char _updated;
	char _childrenUpdated;
	char _subtreeUpdated;
	IKDOMNode* _ownerJSNode;
	IKViewElementStyleComposer* _styleComposer;
	NSMutableDictionary* _featuresMap;

}

@property (assign,nonatomic,__weak) IKDOMNode * ownerJSNode;                             //@synthesize ownerJSNode=_ownerJSNode - In the implementation block
@property (assign,getter=isUpdated,nonatomic) char updated;                              //@synthesize updated=_updated - In the implementation block
@property (assign,getter=isChildrenUpdated,nonatomic) char childrenUpdated;              //@synthesize childrenUpdated=_childrenUpdated - In the implementation block
@property (assign,getter=isSubtreeUpdated,nonatomic) char subtreeUpdated;                //@synthesize subtreeUpdated=_subtreeUpdated - In the implementation block
@property (nonatomic,retain) IKViewElementStyleComposer * styleComposer;                 //@synthesize styleComposer=_styleComposer - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * featuresMap;                          //@synthesize featuresMap=_featuresMap - In the implementation block
+(id)jsNodeDataForNode:(xmlNode*)arg1 create:(char)arg2 ;
-(void)setUpdated:(char)arg1 ;
-(void)setSubtreeUpdated:(char)arg1 ;
-(char)isSubtreeUpdated;
-(char)isChildrenUpdated;
-(void)setChildrenUpdated:(char)arg1 ;
-(IKDOMNode *)ownerJSNode;
-(NSMutableDictionary *)featuresMap;
-(void)setFeaturesMap:(NSMutableDictionary *)arg1 ;
-(void)setFeature:(id)arg1 forName:(id)arg2 ;
-(id)featureForName:(id)arg1 ;
-(void)setOwnerJSNode:(IKDOMNode *)arg1 ;
-(IKViewElementStyleComposer *)styleComposer;
-(void)setStyleComposer:(IKViewElementStyleComposer *)arg1 ;
-(char)isUpdated;
@end

