/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString, IKDOMNode, NSDate;


@protocol IKJSDOMEvent <JSExport>
@property (nonatomic,retain,readonly) NSString * type; 
@property (nonatomic,retain,readonly) IKDOMNode * target; 
@property (nonatomic,retain,readonly) IKDOMNode * currentTarget; 
@property (nonatomic,readonly) int eventPhase; 
@property (nonatomic,readonly) char bubbles; 
@property (nonatomic,readonly) char cancelable; 
@property (nonatomic,readonly) NSDate * timeStamp; 
@property (nonatomic,readonly) char defaultPrevented; 
@required
-(NSString *)type;
-(IKDOMNode *)target;
-(NSDate *)timeStamp;
-(id)initWithType:(id)arg1 eventInit:(id)arg2;
-(IKDOMNode *)currentTarget;
-(int)eventPhase;
-(char)bubbles;
-(char)cancelable;
-(char)defaultPrevented;
-(void)stopPropagation;
-(void)preventDefault;
-(void)stopImmediatePropagation;

@end

