/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:13 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ITMLKit/IKJSEventListenerObject.h>
#import <ITMLKit/IKJSPlayer.h>
@class IKJSMediaItem, IKJSPlaylist;


@protocol IKJSPlayer <JSExport>
@property (nonatomic,readonly) IKJSMediaItem * currentMediaItem; 
@property (nonatomic,retain) IKJSPlaylist * playlist; 
@property (nonatomic,readonly) char paused; 
@property (nonatomic,readonly) char ended; 
@property (nonatomic,readonly) char seeking; 
@property (nonatomic,readonly) char playing; 
@required
-(void)play;
-(void)setPlaybackRate:(double)arg1;
-(IKJSMediaItem *)currentMediaItem;
-(char)seeking;
-(void)setCurrentTime:(double)arg1;
-(id)init;
-(void)stop;
-(char)paused;
-(void)pause;
-(char)ended;
-(void)setPlaylist:(id)arg1;
-(IKJSPlaylist *)playlist;
-(char)playing;

@end


@class IKJSMediaItem, IKJSPlaylist, NSMutableDictionary, IKAppPlayerBridge;

@interface IKJSPlayer : IKJSEventListenerObject <IKJSPlayer> {

	IKJSPlaylist* _playlist;
	int _playerState;
	char _holdingSelfReference;
	NSMutableDictionary* _observedMetadataKeys;
	IKAppPlayerBridge* _bridge;

}

@property (nonatomic,readonly) IKJSMediaItem * currentMediaItem; 
@property (nonatomic,retain) IKJSPlaylist * playlist; 
@property (nonatomic,readonly) IKAppPlayerBridge * bridge;                    //@synthesize bridge=_bridge - In the implementation block
@property (nonatomic,readonly) char paused; 
@property (nonatomic,readonly) char ended; 
@property (nonatomic,readonly) char seeking; 
@property (nonatomic,readonly) char playing; 
-(void)play;
-(void)setPlaybackRate:(double)arg1 ;
-(IKJSMediaItem *)currentMediaItem;
-(char)seeking;
-(void)setCurrentTime:(double)arg1 ;
-(id)init;
-(int)state;
-(void)stop;
-(char)paused;
-(void)pause;
-(IKAppPlayerBridge *)bridge;
-(void)stateDidChange:(id)arg1 ;
-(void)timedMetadataDidChange:(id)arg1 value:(id)arg2 ;
-(void)removeEventListener:(id)arg1 :(id)arg2 ;
-(char)ended;
-(void)setPlaylist:(IKJSPlaylist *)arg1 ;
-(IKJSPlaylist *)playlist;
-(char)playing;
-(void)addEventListener:(id)arg1 :(id)arg2 :(id)arg3 ;
@end

