/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ITMLKit/IKViewElement.h>

@class NSArray, IKAppDOMPlayer;

@interface IKPlaylistElement : IKViewElement

@property (nonatomic,retain,readonly) NSArray * items; 
@property (nonatomic,retain,readonly) IKAppDOMPlayer * player; 
+(id)supportedFeatures;
-(NSArray *)items;
-(IKAppDOMPlayer *)player;
@end

