/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:25 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AppLaunchStats.framework/AppLaunchStats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface AppLaunchStatsLaunchObject : NSObject {

	/*^block*/id aplsLaunchQueueBlock;
	NSString* bundleID;

}

@property (copy) id aplsLaunchQueueBlock; 
@property (nonatomic,retain) NSString * bundleID; 
-(id)aplsLaunchQueueBlock;
-(void)setAplsLaunchQueueBlock:(id)arg1 ;
-(NSString *)bundleID;
-(void)setBundleID:(NSString *)arg1 ;
@end

