/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUINavigationDocumentDelegate <NSObject>
@optional
-(void)navigationDocumentStackDidChange:(id)arg1;
-(id)jsNavigationDocumentForNavigationDocumentController:(id)arg1 inContext:(id)arg2;
-(void)navigationDocumentController:(id)arg1 requestsAccessToAppContextUsingBlock:(/*^block*/id)arg2;

@end

