/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>

@class SKUIClientContext, NSString, NSOperationQueue, SKUIRedeemPreflightOperation, SKUIRedeemConfiguration, SKUIRedeemStepViewController;

@interface SKUIRedeemViewController : UINavigationController {

	char _attempsAutomaticRedeem;
	char _cameraRedeemEnabled;
	int _category;
	SKUIClientContext* _clientContext;
	NSString* _initialCode;
	NSOperationQueue* _operationQueue;
	SKUIRedeemPreflightOperation* _preflightOperation;
	SKUIRedeemConfiguration* _redeemConfiguration;
	SKUIRedeemStepViewController* _rootViewController;
	int _initialBarStyle;

}

@property (nonatomic,readonly) int category;                                 //@synthesize category=_category - In the implementation block
@property (assign,nonatomic) char attempsAutomaticRedeem;                    //@synthesize attempsAutomaticRedeem=_attempsAutomaticRedeem - In the implementation block
@property (nonatomic,copy) NSString * initialCode;                           //@synthesize initialCode=_initialCode - In the implementation block
@property (nonatomic,retain) SKUIClientContext * clientContext;              //@synthesize clientContext=_clientContext - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;              //@synthesize operationQueue=_operationQueue - In the implementation block
-(void)_cancelButtonAction:(id)arg1 ;
-(int)category;
-(unsigned)supportedInterfaceOrientations;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(NSOperationQueue *)operationQueue;
-(void)setClientContext:(SKUIClientContext *)arg1 ;
-(SKUIClientContext *)clientContext;
-(NSString *)initialCode;
-(char)attempsAutomaticRedeem;
-(void)_finishPreflightWithResult:(id)arg1 ;
-(id)_newRootViewController;
-(void)_loadRootViewController;
-(void)_attemptAutomaticRedeemWithMetadata:(id)arg1 ;
-(void)_showRootViewController;
-(id)initWithRedeemCategory:(int)arg1 ;
-(void)setInitialCode:(NSString *)arg1 ;
-(void)redeemAgainAnimated:(char)arg1 ;
-(void)setAttempsAutomaticRedeem:(char)arg1 ;
@end

