/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:42 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/SKUISettingsHeaderFooterDescription.h>

@class SKUIClientContext;

@interface SKUIHandleRulesSettingsHeaderFooterDescription : SKUISettingsHeaderFooterDescription {

	SKUIClientContext* _clientContext;
	char _showInvalid;

}

@property (assign,nonatomic) char showInvalid;              //@synthesize showInvalid=_showInvalid - In the implementation block
-(id)text;
-(id)initWithClientContext:(id)arg1 ;
-(Class)_viewClassForSettingsHeaderFooterDescription:(id)arg1 ;
-(char)showInvalid;
-(void)setShowInvalid:(char)arg1 ;
@end

