/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/StoreKitUI-Structs.h>
#import <UIKit/UIView.h>

@protocol SKUIEditorialLinkViewDelegate;
@class NSMutableArray, UIColor, SKUIEditorialLinkLayout;

@interface SKUIEditorialLinkView : UIView {

	NSMutableArray* _buttons;
	id<SKUIEditorialLinkViewDelegate> _delegate;
	UIColor* _highlightedTextColor;
	int _horizontalAlignment;
	SKUIEditorialLinkLayout* _layout;
	UIColor* _textColor;

}

@property (assign,nonatomic,__weak) id<SKUIEditorialLinkViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int horizontalAlignment;                                        //@synthesize horizontalAlignment=_horizontalAlignment - In the implementation block
@property (nonatomic,retain) SKUIEditorialLinkLayout * linkLayout;                           //@synthesize layout=_layout - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(void)setDelegate:(id<SKUIEditorialLinkViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<SKUIEditorialLinkViewDelegate>)delegate;
-(void)tintColorDidChange;
-(id)_newButton;
-(void)setColoringWithColorScheme:(id)arg1 ;
-(void)_linkButtonAction:(id)arg1 ;
-(void)setHorizontalAlignment:(int)arg1 ;
-(void)setLinkLayout:(SKUIEditorialLinkLayout *)arg1 ;
-(int)horizontalAlignment;
-(SKUIEditorialLinkLayout *)linkLayout;
@end

