/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUISettingsGroupsDescriptionDelegate <NSObject>
@required
-(void)settingsGroupsDescription:(id)arg1 deletedSettingAtIndexPath:(id)arg2;
-(void)settingsGroupsDescription:(id)arg1 deletedSettingsGroupAtIndex:(unsigned)arg2;
-(void)settingsGroupsDescription:(id)arg1 didUpdateSettingsDescription:(id)arg2;
-(void)settingsGroupsDescription:(id)arg1 dismissViewController:(id)arg2 animated:(char)arg3 completion:(/*^block*/id)arg4;
-(void)settingsGroupsDescription:(id)arg1 presentViewController:(id)arg2 animated:(char)arg3 completion:(/*^block*/id)arg4;
-(id)settingsGroupsDescription:(id)arg1 viewForSettingAtIndexPath:(id)arg2;
-(void)settingsGroupsDescriptionDidUpdateValidity:(id)arg1;

@end

