/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:47 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <StoreKitUI/StoreKitUI-Structs.h>
@class NSMutableArray;

@interface SKUIShelfLayoutData : NSObject {

	float _columnSpacing;
	NSMutableArray* _columnWidths;
	UIEdgeInsets _contentInset;
	int _numberOfRows;
	float* _rowHeights;

}

@property (nonatomic,readonly) float columnSpacing;                  //@synthesize columnSpacing=_columnSpacing - In the implementation block
@property (nonatomic,readonly) int numberOfRows;                     //@synthesize numberOfRows=_numberOfRows - In the implementation block
@property (assign,nonatomic) UIEdgeInsets contentInset;              //@synthesize contentInset=_contentInset - In the implementation block
@property (nonatomic,readonly) CGSize totalContentSize; 
@property (nonatomic,readonly) int numberOfColumns; 
-(void)dealloc;
-(int)numberOfColumns;
-(UIEdgeInsets)contentInset;
-(void)setContentInset:(UIEdgeInsets)arg1 ;
-(int)numberOfRows;
-(CGSize)sizeForItemAtIndex:(int)arg1 ;
-(CGSize)totalContentSize;
-(float)columnSpacing;
-(void)enumerateColumnsUsingBlock:(/*^block*/id)arg1 ;
-(void)enumerateRowsUsingBlock:(/*^block*/id)arg1 ;
-(float)columnWidthForIndex:(int)arg1 ;
-(float)rowHeightForIndex:(int)arg1 ;
-(id)initWithNumberOfRows:(int)arg1 columnSpacing:(float)arg2 ;
-(void)reloadWithItemCount:(int)arg1 sizeBlock:(/*^block*/id)arg2 ;
@end

