/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/StoreKitUI-Structs.h>
#import <StoreKitUI/SKUIAttributedStringView.h>

@class SKUIAttributedStringView;

@interface SKUIAttributedStringWrapperView : SKUIAttributedStringView {

	SKUIAttributedStringView* _delegateView;

}

@property (nonatomic,readonly) SKUIAttributedStringView * delegateView;              //@synthesize delegateView=_delegateView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setTextColor:(id)arg1 ;
-(id)layout;
-(id)textColor;
-(float)baselineOffset;
-(void)setLayout:(id)arg1 ;
-(float)firstBaselineOffset;
-(void)setStringTreatment:(int)arg1 ;
-(void)setTreatmentColor:(id)arg1 ;
-(void)setTextColorFollowsTintColor:(char)arg1 ;
-(void)setRequiredBadges:(id)arg1 ;
-(char)usesTallCharacterSet;
-(void)setFirstLineTopInset:(int)arg1 ;
-(id)requiredBadges;
-(int)stringTreatment;
-(id)treatmentColor;
-(int)firstLineTopInset;
-(char)textColorFollowsTintColor;
-(SKUIAttributedStringView *)delegateView;
@end

