/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:40 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUISlideshowViewControllerDataSource <NSObject>
@optional
-(id)slideshowViewController:(id)arg1 imageAtIndex:(int)arg2;
-(id)slideshowViewController:(id)arg1 imageURLAtIndex:(int)arg2 size:(CGSize*)arg3;

@required
-(int)numberOfItemsInSlideshowViewController:(id)arg1;

@end

