/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SKUIItemOfferButtonState : NSObject {

	char _highlighted;
	char _showingConfirmation;
	char _hasImage;
	int _progressType;

}

@property (assign,nonatomic) char highlighted;                      //@synthesize highlighted=_highlighted - In the implementation block
@property (assign,nonatomic) char showingConfirmation;              //@synthesize showingConfirmation=_showingConfirmation - In the implementation block
@property (assign,nonatomic) int progressType;                      //@synthesize progressType=_progressType - In the implementation block
@property (assign,nonatomic) char hasImage;                         //@synthesize hasImage=_hasImage - In the implementation block
-(void)setHighlighted:(char)arg1 ;
-(char)highlighted;
-(void)setProgressType:(int)arg1 ;
-(char)hasImage;
-(char)showingConfirmation;
-(void)setShowingConfirmation:(char)arg1 ;
-(int)progressType;
-(void)setHasImage:(char)arg1 ;
@end

