/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/SKUIDonationStepViewController.h>
#import <StoreKitUI/SKUIDonationConfigurationObserver.h>

@class SKUIDonationAmountView, SKUIGiftValidationResponse, SKUIGiftPurchaseRequest, SKUIGiftValidator, NSString;

@interface SKUIDonationAmountViewController : SKUIDonationStepViewController <SKUIDonationConfigurationObserver> {

	SKUIDonationAmountView* _amountView;
	SKUIGiftValidationResponse* _lastValidationResponse;
	SKUIGiftPurchaseRequest* _purchaseRequest;
	char _tappedNextWhileValidating;
	SKUIGiftValidator* _validator;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_cancelButtonAction:(id)arg1 ;
-(void)dealloc;
-(void)loadView;
-(void)_finishValidationWithResponse:(id)arg1 error:(id)arg2 ;
-(void)_finishPurchaseWithResult:(char)arg1 errorMessage:(id)arg2 ;
-(id)initWithCharity:(id)arg1 configuration:(id)arg2 ;
-(void)_donateButtonAction:(id)arg1 ;
-(void)_amountChangedNotification:(id)arg1 ;
-(void)_validateDonation:(id)arg1 ;
-(void)_performActionAfterValidation;
-(void)_setDonationButtonEnabled:(char)arg1 ;
-(void)_reenableAfterFailure;
-(void)donationConfigurationController:(id)arg1 didLoadLogoForCharity:(id)arg2 ;
@end

