/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:48 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUISearchFieldDelegate <NSObject>
@optional
-(void)searchFieldController:(id)arg1 requestSearch:(id)arg2;
-(void)searchFieldController:(id)arg1 requestSearchWithURL:(id)arg2 metricsEvent:(id)arg3;
-(void)searchFieldController:(id)arg1 requestSearchWithSearchTerm:(id)arg2 metricsEvent:(id)arg3;
-(void)searchFieldController:(id)arg1 searchBarDidChangeText:(id)arg2;
-(char)searchFieldControllerShouldBeginEditing:(id)arg1;

@end

