/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/_NSCoreManagedObjectID.h>

@interface _NSScalarObjectID : _NSCoreManagedObjectID
-(long long)_referenceData64;
-(id)initWithPK64:(long long)arg1 ;
-(id)_retainedURIString;
-(int)_getURIBytes:(char*)arg1 length:(int)arg2 ;
-(void)dealloc;
@end

