/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSKnownKeysDictionary;

@interface _PFTempNestedSnapshot : NSObject {

	NSKnownKeysDictionary* _snapshot;
	unsigned long _version;

}
-(unsigned)_versionNumber;
-(const id*)knownKeyValuesPointer;
-(id)_snapshot_;
-(id)initWithOwnedKKsD:(id)arg1 andVersion:(unsigned long)arg2 ;
-(id)valueForKey:(id)arg1 ;
-(void)dealloc;
@end

