/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:34 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/CoreData-Structs.h>
#import <CoreData/NSSQLStatement.h>

@interface NSSQLiteStatement : NSSQLStatement {

	sqlite3_stmtRef _cachedSQLiteStatement;

}
-(sqlite3_stmtRef)cachedSQLiteStatement;
-(void)setCachedSQLiteStatement:(sqlite3_stmtRef)arg1 ;
-(void)dealloc;
-(void)clearCaches;
-(void)finalize;
@end

