/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMHTTPAuthenticationHandler.h>

@class NSString;

@interface ACMHTTPExternalAuthenticationHandler : ACMHTTPAuthenticationHandler {

	NSString* _password;

}

@property (nonatomic,copy) NSString * password;              //@synthesize password=_password - In the implementation block
-(void)dealloc;
-(NSString *)password;
-(void)setPassword:(NSString *)arg1 ;
-(char)updatePublicKeyWithResponse:(id)arg1 ;
-(void)didStopWithResponse:(id)arg1 ;
@end

