/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:28 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FMF.framework/FMF
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface FMFAppSession : NSObject
+(id)sharedInstance;
-(id)_fmfAppAccountFromAOSAccount:(id)arg1 ;
-(void)startListeningForFMFAppPushInEnvironment:(id)arg1 withMessageHandler:(/*^block*/id)arg2 tokenHandler:(/*^block*/id)arg3 ;
-(void)stopListeningForFMFAppPush;
-(void)locationAuthorizationForShareMyLocationWithCompletion:(/*^block*/id)arg1 ;
-(id)thisDeviceId;
-(void)retrieveFMFAccountWithCompletion:(/*^block*/id)arg1 ;
-(void)renewFMFAccountCredentialsWithCompletion:(/*^block*/id)arg1 ;
@end

