/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:29 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <FTServices/FTServices-Structs.h>
@class NSDictionary;

@interface FTEntitlementSupport : NSObject {

	CTServerConnectionRef _ctServerConnection;
	CFStringRef _entitlementStatus;

}

@property (nonatomic,readonly) char faceTimeNonWiFiEntitled; 
@property (nonatomic,retain,readonly) NSDictionary * registrationState; 
+(id)sharedInstance;
-(id)init;
-(NSDictionary *)registrationState;
-(char)_registerForCTEntitlementNotifications;
-(void)_unregisterForCTEntitlementNotifications;
-(void)_handleEntitlementNotification:(CFDictionaryRef)arg1 ;
-(void)_registrationStateChanged;
-(id)_rawEntitlementValue;
-(void)_cleanupMachInfo;
-(char)_setupCTServerConnection;
-(char)_disconnectCTServerConnection;
-(char)_reconnectCTServerConnectionIfNecessary;
-(void)_handleCTServiceRequestName:(CFStringRef)arg1 userInfo:(CFDictionaryRef)arg2 contextInfo:(void*)arg3 ;
-(char)faceTimeNonWiFiEntitled;
@end

