/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:20 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <DataAccess/DAMailboxRequest.h>

@interface DAMailboxDeleteMessageRequest : DAMailboxRequest
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)initRequestWithMessageID:(id)arg1 ;
@end

