/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/VisualAlert.framework/VisualAlert
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <VisualAlert/__AXVisualAlertSBLockScreenNotificationListController_super.h>

@interface AXVisualAlertSBLockScreenNotificationListController : __AXVisualAlertSBLockScreenNotificationListController_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(void)turnOnScreenIfNecessaryForItem:(id)arg1 ;
@end

