/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:14 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/RDSupport.framework/RDSupport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSXPCConnection, NSString;

@interface RDDaemonConnection : NSObject {

	NSXPCConnection* _xpcConnection;
	NSString* _lastAppLaunchBundleID;

}
+(id)sharedConnection;
-(id)xpcConnection;
-(void)carouselLaunchingAppWithBundleID:(id)arg1 ;
-(void)quickboardAvailableForAppWithBundleID:(id)arg1 ;
-(void)emojiAvailableForAppWithBundleID:(id)arg1 ;
-(void)clearConnection;
-(void)quickboardNoLongerAvailableForAppWithBundleID:(id)arg1 ;
-(void)pingRetailDaemon;
-(void)carouselShowingGlanceWithID:(id)arg1 ;
-(void)carouselShowingAlertWithID:(id)arg1 ;
-(void)carouselWillLaunchAppWithBundleID:(id)arg1 ;
-(void)carouselShowingAppLauncher;
-(void)carouselShowingClock;
-(void)carouselShowingNotificationCenter;
-(void)rebootCompanion:(char)arg1 gizmo:(char)arg2 ;
-(void)enteringWatchFaceSwitcher;
-(void)leavingWachFaceSwitcher;
-(void)enteringWatchFaceCustomization;
-(void)leavingWatchFaceCustomization;
-(void)quickboardCompositionViewControllerWillBePresentedForAppWithBundleID:(id)arg1 ;
-(void)quickboardCompositionViewControllerWillBeDismissedForAppWithBundleID:(id)arg1 ;
-(void)quickboardEmojiCompositionViewControllerWillBePresentedForAppWithBundleID:(id)arg1 ;
-(void)enteringPersonPicker;
-(void)leavingPersonPicker;
-(void)screenSaverWasDismissed;
-(char)_previousApplicationWasAnAlert;
@end

