/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:26 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <HealthKit/HealthKit-Structs.h>
#import <HealthKit/_HKMetadataFilter.h>

@interface _HKComparisonMetadataFilter : _HKMetadataFilter {

	id _value;

}

@property (nonatomic,readonly) id value;              //@synthesize value=_value - In the implementation block
+(char)_acceptsOperatorType:(unsigned)arg1 ;
+(id)filterWithKey:(id)arg1 operatorType:(unsigned)arg2 value:(id)arg3 ;
+(char)supportsSecureCoding;
-(id)_initWithKey:(id)arg1 operatorType:(unsigned)arg2 value:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)value;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)acceptsDataObject:(id)arg1 ;
@end

