/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:09 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/CoreDuetDebugLogging
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CDDebug : NSObject {

	char verboseMode;

}
-(id)init;
-(void)error:(int)arg1 ;
-(id)initWithVerboseMode:(char)arg1 ;
-(void)log:(const char*)arg1 ;
@end

