/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:55 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotoLibrary/PhotoLibrary-Structs.h>
#import <UIKit/UIToolbar.h>

@class UIToolbar;

@interface PLToolbar : UIToolbar {

	unsigned _backgroundHidden : 1;
	unsigned _backgroundAlwaysVisible : 1;
	UIToolbar* _persistentToolbar;

}

@property (assign,getter=isBackgroundHidden,nonatomic) char backgroundHidden; 
@property (assign,getter=isBackgroundAlwaysVisible,nonatomic) char backgroundAlwaysVisible; 
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(char)isBackgroundHidden;
-(void)setBackgroundHidden:(char)arg1 ;
-(char)isBackgroundAlwaysVisible;
-(void)setBackgroundAlwaysVisible:(char)arg1 ;
@end

