/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:26 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iCalendar/ICSProperty.h>

@interface ICSMultiValueProperty : ICSProperty
-(id)initWithValue:(id)arg1 type:(unsigned)arg2 ;
-(void)setValue:(id)arg1 type:(unsigned)arg2 ;
-(id)value;
-(id)values;
-(void)_ICSStringWithOptions:(unsigned)arg1 appendingToString:(id)arg2 ;
-(char)isMultiValued;
-(void)_setParsedValues:(id)arg1 type:(unsigned)arg2 ;
-(void)setValues:(id)arg1 valueType:(unsigned)arg2 ;
@end

