/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:27 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/LocalAuthentication.framework/Support/SharedUtils.framework/SharedUtils
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSData;

@interface LAACMHelper : NSObject {

	NSData* _externalizedContext;

}

@property (nonatomic,readonly) NSData * externalizedContext;              //@synthesize externalizedContext=_externalizedContext - In the implementation block
-(char)performBlock:(/*^block*/id)arg1 error:(id*)arg2 ;
-(char)addCredentialOfType:(unsigned)arg1 afterPerformingBlock:(/*^block*/id)arg2 error:(id*)arg3 ;
-(id)initWithExternalizedContext:(id)arg1 ;
-(char)addPassphraseCredentialWithPurpose:(unsigned)arg1 passphrase:(id)arg2 error:(id*)arg3 ;
-(char)removeCredentialsOfType:(unsigned)arg1 error:(id*)arg2 ;
-(NSData *)externalizedContext;
@end

