/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:27 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <iTunesStore/iTunesStore-Structs.h>
@interface OpenURLTarget : NSObject {

	unsigned _applicationState;
	SCD_Struct_Op9 _targetData;
	int _targetIndex;

}
-(id)init;
-(id)description;
-(int)compare:(id)arg1 ;
-(id)initWithTargetIdentifier:(id)arg1 ;
-(id)copyURLForURL:(id)arg1 ;
@end

