/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/AddressBookUIFramework.axbundle/AddressBookUIFramework
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AddressBookUIFramework/AddressBookUIFramework-Structs.h>
#import <AddressBookUIFramework/__ABMultiCellContentView_RowsAccessibility_super.h>

@interface ABMultiCellContentView_RowsAccessibility : __ABMultiCellContentView_RowsAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(CGSize)layoutSubviewsForView:(id)arg1 usingSize:(CGSize)arg2 propertyGroup:(id)arg3 info:(id)arg4 styleProvider:(id)arg5 whenEditing:(char)arg6 ;
-(void)updateSubviewsForNewStateAnimated:(char)arg1 ;
@end

