/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:35 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SportsVoices.framework/SportsVoices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SportsVoices/DecomposerDelegateProtocol.h>

@class NSDictionary;

@interface DecomposerDelegate : NSObject <DecomposerDelegateProtocol> {

	NSDictionary* _overridesForWhole;
	NSDictionary* _overridesForParts;

}
-(void)dealloc;
-(id)decomposer:(id)arg1 decompositionOf:(id)arg2 isSubsetOfWhole:(char)arg3 ;
-(id)initWithWholeOverrides:(id)arg1 partOverrides:(id)arg2 ;
@end

