/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:55 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol QLRemotePreviewContentControllerProtocol <QLPreviewContentControllerProtocol>
@required
-(void)_willTransitionToSize:(CGSize)arg1;
-(void)_setNavigationBarVerticalOffset:(float)arg1;
-(void)_setNumberOfPreviewItems:(int)arg1;
-(void)_setTransitioning:(char)arg1;
-(void)_getNumberOfPagesForSize:(CGSize)arg1 withHandler:(/*^block*/id)arg2;
-(void)_prepareForDrawingPages:(NSRange)arg1 withSize:(CGSize)arg2;
-(void)_getPDFPageAtIndex:(int)arg1 handler:(/*^block*/id)arg2;

@end

