/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:44 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/Metal.framework/Metal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Metal/Metal-Structs.h>
#import <Metal/NSCopying.h>
#import <Metal/NSCoding.h>

@class NSString;

@interface MTLResourceAllocationInfo : NSObject <NSCopying, NSCoding> {

	char _pageoffRequired;
	char _purgeable;
	NSString* _memoryPool;
	unsigned _virtualSize;
	unsigned _residentSize;
	unsigned _dirtySize;
	unsigned long long _uniqueIdentifier;

}

@property (readonly) NSString * memoryPool;                            //@synthesize memoryPool=_memoryPool - In the implementation block
@property (readonly) unsigned virtualSize;                             //@synthesize virtualSize=_virtualSize - In the implementation block
@property (readonly) unsigned residentSize;                            //@synthesize residentSize=_residentSize - In the implementation block
@property (readonly) unsigned dirtySize;                               //@synthesize dirtySize=_dirtySize - In the implementation block
@property (readonly) char pageoffRequired;                             //@synthesize pageoffRequired=_pageoffRequired - In the implementation block
@property (readonly) char purgeable;                                   //@synthesize purgeable=_purgeable - In the implementation block
@property (readonly) unsigned long long uniqueIdentifier;              //@synthesize uniqueIdentifier=_uniqueIdentifier - In the implementation block
-(char)purgeable;
-(NSString *)memoryPool;
-(unsigned)residentSize;
-(unsigned)dirtySize;
-(char)pageoffRequired;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(unsigned)virtualSize;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)uniqueIdentifier;
@end

