/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:49 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libAWDSupportFramework.dylib/NSCopying.h>

@class NSString;

@interface AWDIDSStreamingReport : PBCodable <NSCopying> {

	unsigned long long _bytesReceived;
	unsigned long long _bytesSent;
	unsigned long long _packetsReceived;
	unsigned long long _packetsSent;
	unsigned long long _priority;
	unsigned long long _samplingInterval;
	unsigned long long _timestamp;
	NSString* _guid;
	NSString* _service;
	NSString* _streamName;
	SCD_Struct_AW11 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                     //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasService; 
@property (nonatomic,retain) NSString * service;                               //@synthesize service=_service - In the implementation block
@property (nonatomic,readonly) char hasStreamName; 
@property (nonatomic,retain) NSString * streamName;                            //@synthesize streamName=_streamName - In the implementation block
@property (assign,nonatomic) char hasSamplingInterval; 
@property (assign,nonatomic) unsigned long long samplingInterval;              //@synthesize samplingInterval=_samplingInterval - In the implementation block
@property (assign,nonatomic) char hasBytesSent; 
@property (assign,nonatomic) unsigned long long bytesSent;                     //@synthesize bytesSent=_bytesSent - In the implementation block
@property (assign,nonatomic) char hasPacketsSent; 
@property (assign,nonatomic) unsigned long long packetsSent;                   //@synthesize packetsSent=_packetsSent - In the implementation block
@property (assign,nonatomic) char hasBytesReceived; 
@property (assign,nonatomic) unsigned long long bytesReceived;                 //@synthesize bytesReceived=_bytesReceived - In the implementation block
@property (assign,nonatomic) char hasPacketsReceived; 
@property (assign,nonatomic) unsigned long long packetsReceived;               //@synthesize packetsReceived=_packetsReceived - In the implementation block
@property (assign,nonatomic) char hasPriority; 
@property (assign,nonatomic) unsigned long long priority;                      //@synthesize priority=_priority - In the implementation block
@property (nonatomic,readonly) char hasGuid; 
@property (nonatomic,retain) NSString * guid;                                  //@synthesize guid=_guid - In the implementation block
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setPriority:(unsigned long long)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)priority;
-(char)hasTimestamp;
-(NSString *)service;
-(void)setService:(NSString *)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setGuid:(NSString *)arg1 ;
-(char)hasGuid;
-(NSString *)guid;
-(void)setBytesSent:(unsigned long long)arg1 ;
-(unsigned long long)bytesSent;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(char)hasService;
-(void)setStreamName:(NSString *)arg1 ;
-(void)setHasBytesSent:(char)arg1 ;
-(char)hasBytesSent;
-(void)setPacketsSent:(unsigned long long)arg1 ;
-(void)setHasPacketsSent:(char)arg1 ;
-(char)hasPacketsSent;
-(void)setBytesReceived:(unsigned long long)arg1 ;
-(void)setHasBytesReceived:(char)arg1 ;
-(char)hasBytesReceived;
-(void)setPacketsReceived:(unsigned long long)arg1 ;
-(void)setHasPacketsReceived:(char)arg1 ;
-(char)hasPacketsReceived;
-(void)setHasPriority:(char)arg1 ;
-(char)hasPriority;
-(char)hasStreamName;
-(unsigned long long)packetsSent;
-(unsigned long long)bytesReceived;
-(unsigned long long)packetsReceived;
-(NSString *)streamName;
-(void)setSamplingInterval:(unsigned long long)arg1 ;
-(void)setHasSamplingInterval:(char)arg1 ;
-(char)hasSamplingInterval;
-(unsigned long long)samplingInterval;
@end

