/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:41 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libAWDSupportFramework.dylib/NSCopying.h>

@class NSString;

@interface AWDIMessageAttachmentDownload : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _attachmentSize;
	unsigned _connectionType;
	unsigned _downloadDuration;
	int _fzError;
	int _genericError;
	NSString* _guid;
	int _linkQuality;
	unsigned _messageError;
	unsigned _tokenError;
	SCD_Struct_AW12 _has;

}

@property (nonatomic,readonly) char hasGuid; 
@property (nonatomic,retain) NSString * guid;                           //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasFzError; 
@property (assign,nonatomic) int fzError;                               //@synthesize fzError=_fzError - In the implementation block
@property (assign,nonatomic) char hasMessageError; 
@property (assign,nonatomic) unsigned messageError;                     //@synthesize messageError=_messageError - In the implementation block
@property (assign,nonatomic) char hasTokenError; 
@property (assign,nonatomic) unsigned tokenError;                       //@synthesize tokenError=_tokenError - In the implementation block
@property (assign,nonatomic) char hasGenericError; 
@property (assign,nonatomic) int genericError;                          //@synthesize genericError=_genericError - In the implementation block
@property (assign,nonatomic) char hasDownloadDuration; 
@property (assign,nonatomic) unsigned downloadDuration;                 //@synthesize downloadDuration=_downloadDuration - In the implementation block
@property (assign,nonatomic) char hasLinkQuality; 
@property (assign,nonatomic) int linkQuality;                           //@synthesize linkQuality=_linkQuality - In the implementation block
@property (assign,nonatomic) char hasConnectionType; 
@property (assign,nonatomic) unsigned connectionType;                   //@synthesize connectionType=_connectionType - In the implementation block
@property (assign,nonatomic) char hasAttachmentSize; 
@property (assign,nonatomic) unsigned attachmentSize;                   //@synthesize attachmentSize=_attachmentSize - In the implementation block
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(char)hasTimestamp;
-(unsigned)connectionType;
-(void)setConnectionType:(unsigned)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setGuid:(NSString *)arg1 ;
-(char)hasGuid;
-(NSString *)guid;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasConnectionType:(char)arg1 ;
-(char)hasConnectionType;
-(void)setLinkQuality:(int)arg1 ;
-(void)setHasLinkQuality:(char)arg1 ;
-(char)hasLinkQuality;
-(int)linkQuality;
-(void)setGenericError:(int)arg1 ;
-(void)setHasGenericError:(char)arg1 ;
-(char)hasGenericError;
-(int)genericError;
-(void)setFzError:(int)arg1 ;
-(void)setHasFzError:(char)arg1 ;
-(char)hasFzError;
-(void)setMessageError:(unsigned)arg1 ;
-(void)setHasMessageError:(char)arg1 ;
-(char)hasMessageError;
-(void)setTokenError:(unsigned)arg1 ;
-(void)setHasTokenError:(char)arg1 ;
-(char)hasTokenError;
-(void)setDownloadDuration:(unsigned)arg1 ;
-(void)setHasDownloadDuration:(char)arg1 ;
-(char)hasDownloadDuration;
-(void)setAttachmentSize:(unsigned)arg1 ;
-(void)setHasAttachmentSize:(char)arg1 ;
-(char)hasAttachmentSize;
-(int)fzError;
-(unsigned)messageError;
-(unsigned)tokenError;
-(unsigned)downloadDuration;
-(unsigned)attachmentSize;
@end

