/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:49 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libAWDSupportFramework.dylib/NSCopying.h>

@interface AWDPowerBBNonDataMetrics : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _aPWakeCacheFlushCnt;
	unsigned _idlePowerMicroWatt;
	unsigned _oOSPowerMicroWatt;
	unsigned _registrationPowerMicroWatt;
	unsigned _scanPowerMicroWatt;
	unsigned _voicePowerMicroWatt;
	SCD_Struct_AW11 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                     //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasScanPowerMicroWatt; 
@property (assign,nonatomic) unsigned scanPowerMicroWatt;                      //@synthesize scanPowerMicroWatt=_scanPowerMicroWatt - In the implementation block
@property (assign,nonatomic) char hasOOSPowerMicroWatt; 
@property (assign,nonatomic) unsigned oOSPowerMicroWatt;                       //@synthesize oOSPowerMicroWatt=_oOSPowerMicroWatt - In the implementation block
@property (assign,nonatomic) char hasRegistrationPowerMicroWatt; 
@property (assign,nonatomic) unsigned registrationPowerMicroWatt;              //@synthesize registrationPowerMicroWatt=_registrationPowerMicroWatt - In the implementation block
@property (assign,nonatomic) char hasIdlePowerMicroWatt; 
@property (assign,nonatomic) unsigned idlePowerMicroWatt;                      //@synthesize idlePowerMicroWatt=_idlePowerMicroWatt - In the implementation block
@property (assign,nonatomic) char hasVoicePowerMicroWatt; 
@property (assign,nonatomic) unsigned voicePowerMicroWatt;                     //@synthesize voicePowerMicroWatt=_voicePowerMicroWatt - In the implementation block
@property (assign,nonatomic) char hasAPWakeCacheFlushCnt; 
@property (assign,nonatomic) unsigned aPWakeCacheFlushCnt;                     //@synthesize aPWakeCacheFlushCnt=_aPWakeCacheFlushCnt - In the implementation block
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(char)hasTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setScanPowerMicroWatt:(unsigned)arg1 ;
-(void)setHasScanPowerMicroWatt:(char)arg1 ;
-(char)hasScanPowerMicroWatt;
-(void)setOOSPowerMicroWatt:(unsigned)arg1 ;
-(void)setHasOOSPowerMicroWatt:(char)arg1 ;
-(char)hasOOSPowerMicroWatt;
-(void)setRegistrationPowerMicroWatt:(unsigned)arg1 ;
-(void)setHasRegistrationPowerMicroWatt:(char)arg1 ;
-(char)hasRegistrationPowerMicroWatt;
-(void)setIdlePowerMicroWatt:(unsigned)arg1 ;
-(void)setHasIdlePowerMicroWatt:(char)arg1 ;
-(char)hasIdlePowerMicroWatt;
-(void)setVoicePowerMicroWatt:(unsigned)arg1 ;
-(void)setHasVoicePowerMicroWatt:(char)arg1 ;
-(char)hasVoicePowerMicroWatt;
-(void)setAPWakeCacheFlushCnt:(unsigned)arg1 ;
-(void)setHasAPWakeCacheFlushCnt:(char)arg1 ;
-(char)hasAPWakeCacheFlushCnt;
-(unsigned)scanPowerMicroWatt;
-(unsigned)oOSPowerMicroWatt;
-(unsigned)registrationPowerMicroWatt;
-(unsigned)idlePowerMicroWatt;
-(unsigned)voicePowerMicroWatt;
-(unsigned)aPWakeCacheFlushCnt;
@end

