/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotoBoothEffects/PhotoBoothEffects-Structs.h>
#import <PhotoBoothEffects/PBFilter.h>

@interface PBMirrorFilter : PBFilter {

	float lastInputX;
	float lastInputY;
	float lastInputAngle;
	BOOL firstTime;
	float inputOrientation;
	CGPoint inputPoint;

}

@property (assign) CGPoint inputPoint; 
@property (assign) float inputOrientation; 
-(CGPoint)inputPoint;
-(void)setDefaults;
-(void)setInputPoint:(CGPoint)arg1 ;
-(id)ciFilterName;
-(char)needsWrapMirror;
-(void)applyParametersToCIFilter:(char)arg1 extent:(CGRect)arg2 ;
-(void)setInputOrientation:(float)arg1 ;
-(float)inputOrientation;
@end

