/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:21 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Foundation/Foundation-Structs.h>
@class NSOutputStream;

@interface _NSJSONWriter : NSObject {

	NSOutputStream* outputStream;
	int kind;
	char* dataBuffer;
	unsigned dataBufferLen;
	unsigned dataLen;
	char freeDataBuffer;
	char* tempBuffer;
	unsigned tempBufferLen;
	int totalDataWritten;

}
-(void)resizeTemporaryBuffer:(unsigned long)arg1 ;
-(id)dataWithRootObject:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
-(int)writeRootObject:(id)arg1 toStream:(id)arg2 options:(unsigned)arg3 error:(id*)arg4 ;
-(int)appendString:(id)arg1 range:(NSRange)arg2 ;
-(void)dealloc;
-(id)init;
-(void)finalize;
@end

