/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:22 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreFoundation/NSMutableDictionary.h>

@class NSMutableDictionary;

@interface NSDirInfo : NSMutableDictionary {

	NSMutableDictionary* dict;

}
-(unsigned)writePath:(id)arg1 docInfo:(id)arg2 errorHandler:(id)arg3 remapContents:(char)arg4 hardLinkPath:(id)arg5 ;
-(id)serializeToData;
-(void)dealloc;
-(unsigned)count;
-(id)init;
-(id)initWithDictionary:(id)arg1 ;
-(void)removeObjectForKey:(id)arg1 ;
-(id)initWithCapacity:(unsigned)arg1 ;
-(id)initWithContentsOfFile:(id)arg1 ;
-(id)initWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned)arg3 ;
-(id)keyEnumerator;
-(id)initWithDictionary:(id)arg1 copyItems:(char)arg2 ;
-(id)objectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
@end

