/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:21 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSFunctionExpression.h>

@interface NSKeyPathExpression : NSFunctionExpression
-(id)CKExpressionValue;
-(id)initWithOperand:(id)arg1 andKeyPath:(id)arg2 ;
-(id)initWithKeyPath:(id)arg1 ;
-(id)predicateFormat;
-(id)pathExpression;
-(void)dealloc;
-(id)keyPath;
@end

