/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:11 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

@class PrefsUILinkLabel, PSSpecifier, NSArray;

@interface ProblemReportingController : PSListController {

	PrefsUILinkLabel* _aboutDiagnosticsLinkLabel;
	PSSpecifier* _diagnosticDataGroupSpecifier;
	PSSpecifier* _filesystemMetadataSnapshotSpecifier;
	NSArray* _appActivitySpecifiers;
	PSSpecifier* _spinnerSpecifier;

}

@property (readonly) PSSpecifier * spinnerSpecifier; 
@property (readonly) PSSpecifier * filesystemMetadataSnapshotSpecifier; 
@property (readonly) NSArray * appActivitySpecifiers; 
+(char)isProblemReportingEnabled;
-(void)dealloc;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(id)specifiers;
-(void)dismissAboutSheet:(id)arg1 ;
-(NSArray *)appActivitySpecifiers;
-(PSSpecifier *)spinnerSpecifier;
-(PSSpecifier *)filesystemMetadataSnapshotSpecifier;
-(void)snapshot:(id)arg1 ;
-(void)setShouldShareAppActivityWithAppDevelopers:(id)arg1 specifier:(id)arg2 ;
-(id)shouldShareAppActivityWithAppDevelopers;
-(void)checkDiagnosticsSessionAvailability;
-(void)setProblemReportingEnabled:(char)arg1 ;
-(void)launchDiagnosticsSession:(id)arg1 ;
-(char)shouldEnableProblemReportingForCheckedSpecifier;
-(void)showAboutDiagnosticsSheet;
-(void)showAboutAppAnalyticsSheet;
@end

