/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:36 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface MusicUpNextViewUpdate : NSObject {

	unsigned _type;
	NSArray* _indexPaths;

}

@property (assign,nonatomic) unsigned type;                     //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSArray * indexPaths;              //@synthesize indexPaths=_indexPaths - In the implementation block
-(id)debugDescription;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(id)_stringForUpdateType:(unsigned)arg1 ;
-(void)setIndexPaths:(NSArray *)arg1 ;
-(NSArray *)indexPaths;
@end

