/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:35 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <FuseUI/MusicEntityProviding.h>

@protocol MusicUpNextCompositeDataSourceDelegate;
@class MusicEntityViewHorizontalLockupContentDescriptor, MusicSectionEntityValueContext, MPUAVPlayer, NSString;

@interface MusicUpNextCompositeDataSource : NSObject <UITableViewDataSource, UITableViewDelegate, MusicEntityProviding> {

	MusicEntityViewHorizontalLockupContentDescriptor* _horizontalLockupContentDescriptor;
	MusicSectionEntityValueContext* _sectionEntityValueContext;
	MPUAVPlayer* _player;
	id<MusicUpNextCompositeDataSourceDelegate> _delegate;

}

@property (nonatomic,retain) MPUAVPlayer * player;                                                                                //@synthesize player=_player - In the implementation block
@property (assign,nonatomic,__weak) id<MusicUpNextCompositeDataSourceDelegate> delegate;                                          //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) MusicEntityViewHorizontalLockupContentDescriptor * horizontalLockupContentDescriptor; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setDelegate:(id<MusicUpNextCompositeDataSourceDelegate>)arg1 ;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(char)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(char)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(id<MusicUpNextCompositeDataSourceDelegate>)delegate;
-(unsigned)numberOfSections;
-(void)configureEntityValueContextOutputForAnyIndexPath:(id)arg1 ;
-(id)indexBarEntryAtIndex:(unsigned)arg1 ;
-(void)configureEntityValueContextOutput:(id)arg1 forIndexPath:(id)arg2 ;
-(void)configureSectionEntityValueContextOutput:(id)arg1 forIndex:(unsigned)arg2 ;
-(id)indexPathForEntityValueContext:(id)arg1 ;
-(char)hasEntitiesNotInLibrary;
-(Class)tableViewCellClass;
-(id)tableViewCellReuseIdentifier;
-(id)tableViewHeaderReusueIdentifier;
-(Class)tableViewHeaderClass;
-(id)horizontalLockupContentDescriptorForIndexPath:(id)arg1 ;
-(void)configureCell:(id)arg1 forIndexPath:(id)arg2 ;
-(float)maxCellHeightForTraitCollection:(id)arg1 ;
-(MusicEntityViewHorizontalLockupContentDescriptor *)horizontalLockupContentDescriptor;
-(void)_configureEntityValueContextOutput:(id)arg1 ;
-(id)updatesForPlayerChangedFromItem:(id)arg1 toItem:(id)arg2 ;
-(char)isNowPlayingDataSource;
-(void)invalidateSizes;
-(char)hasEntities;
-(id)entityValueProviderAtIndexPath:(id)arg1 ;
-(unsigned)numberOfEntitiesInSection:(unsigned)arg1 ;
-(unsigned)numberOfIndexBarEntries;
-(unsigned)sectionForSectionIndexBarEntryAtIndex:(unsigned)arg1 ;
-(void)setPlayer:(MPUAVPlayer *)arg1 ;
-(MPUAVPlayer *)player;
@end

