/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:38 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicPlaybackProgressScrubbing.h>

@class MPUContentItemIdentifierCollection, NSHashTable, MusicPlaybackProgressScrubberController, MPAVController, NSString;

@interface MusicEntityPlaybackStatusController : NSObject <MusicPlaybackProgressScrubbing> {

	char _alwaysLive;
	MPUContentItemIdentifierCollection* _currentContainerIdentifierCollection;
	MPUContentItemIdentifierCollection* _currentItemIdentifierCollection;
	double _playbackCurrentTime;
	double _playbackCurrentTimeOriginatingTime;
	int _playbackDisplayState;
	double _playbackDuration;
	float _playbackRate;
	NSHashTable* _observers;
	MusicPlaybackProgressScrubberController* _playbackProgressScrubberController;
	MPAVController* _player;

}

@property (nonatomic,readonly) MPAVController * player;                                                      //@synthesize player=_player - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,getter=isAlwaysLive,nonatomic) char alwaysLive; 
@property (nonatomic,readonly) int currentScrubSpeed; 
@property (assign,nonatomic,__weak) id<MusicPlaybackProgressScrubberDelegate> scrubberDelegate; 
@property (nonatomic,readonly) double effectiveCurrentTime; 
@property (assign,nonatomic) float rate; 
@property (assign,getter=isScrubbingEnabled,nonatomic) char scrubbingEnabled; 
@property (assign,nonatomic) double totalDuration; 
-(id)initWithPlayer:(id)arg1 ;
-(char)isAlwaysLive;
-(void)_playerItemWillChangeNotification:(id)arg1 ;
-(int)currentScrubSpeed;
-(id<MusicPlaybackProgressScrubberDelegate>)scrubberDelegate;
-(void)setScrubberDelegate:(id<MusicPlaybackProgressScrubberDelegate>)arg1 ;
-(void)setCurrentTime:(double)arg1 ;
-(void)dealloc;
-(double)playbackCurrentTime;
-(void)addPlaybackStatusObserver:(id)arg1 ;
-(void)removePlaybackStatusObserver:(id)arg1 ;
-(id)playbackStatusForContainerIdentifierCollection:(id)arg1 itemIdentifierCollection:(id)arg2 ;
-(void)_enumerateObserversUsingBlock:(/*^block*/id)arg1 ;
-(void)_playerContentsDidChangeNotification:(id)arg1 ;
-(double)effectiveCurrentTime;
-(char)_setCurrentTime:(double)arg1 ;
-(void)cancelScrubbing;
-(void)setAlwaysLive:(char)arg1 ;
-(char)isScrubbingEnabled;
-(void)setScrubbingEnabled:(char)arg1 ;
-(double)totalDuration;
-(void)setTotalDuration:(double)arg1 ;
-(void)_playerPlaybackStateDidChangeNotification:(id)arg1 ;
-(void)_itemContentItemIdentifierCollectionDidChangeNotification:(id)arg1 ;
-(void)_feederContentItemIdentifierCollectionDidChangeNotification:(id)arg1 ;
-(void)_getContainerIdentifierCollection:(out id*)arg1 itemIdentifierCollection:(out id*)arg2 forItem:(id)arg3 ;
-(void)_sendPlaybackStatusDidChange;
-(id)_playbackStatusForPlaybackDisplayState:(int)arg1 ;
-(void)_updateCurrentPlaybackIdentifierSet;
-(float)rate;
-(void)setRate:(float)arg1 ;
-(MPAVController *)player;
@end

