/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:39 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UINavigationController, MusicJSManagedObject, SKUINavigationDocumentController;

@interface MusicModalNavigationStackItem : NSObject {

	UINavigationController* _navigationController;
	MusicJSManagedObject* _jsNavigationDocumentManagedObject;
	int _lastNavigationControllerOperation;
	SKUINavigationDocumentController* _navigationDocumentController;

}

@property (setter=setJSNavigationDocumentManagedObject:,nonatomic,retain) MusicJSManagedObject * jsNavigationDocumentManagedObject;              //@synthesize jsNavigationDocumentManagedObject=_jsNavigationDocumentManagedObject - In the implementation block
@property (assign,nonatomic) int lastNavigationControllerOperation;                                                                              //@synthesize lastNavigationControllerOperation=_lastNavigationControllerOperation - In the implementation block
@property (nonatomic,readonly) UINavigationController * navigationController; 
@property (nonatomic,retain) SKUINavigationDocumentController * navigationDocumentController;                                                    //@synthesize navigationDocumentController=_navigationDocumentController - In the implementation block
-(UINavigationController *)navigationController;
-(MusicJSManagedObject *)jsNavigationDocumentManagedObject;
-(int)lastNavigationControllerOperation;
-(void)setLastNavigationControllerOperation:(int)arg1 ;
-(void)setJSNavigationDocumentManagedObject:(id)arg1 ;
-(id)initWithNavigationController:(id)arg1 ;
-(void)setNavigationDocumentController:(SKUINavigationDocumentController *)arg1 ;
-(SKUINavigationDocumentController *)navigationDocumentController;
@end

