/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MusicVerticalScrollingContainerItemContextDelegate;
@class UIScrollView, UICollectionView, UICollectionViewCell, NSMutableArray, MusicVerticalScrollingContainerItem, UIView;

@interface MusicVerticalScrollingContainerItemContext : NSObject {

	UIScrollView* _contentScrollView;
	UICollectionView* _containerCollectionView;
	UICollectionViewCell* _containerCell;
	char _contentScrollViewCanPanVertically;
	char _contentScrollViewScrollsToTop;
	char _hasSetupContentScrollView;
	char _isChangingContentScrollViewContentOffset;
	float _lastSeenContentHeight;
	unsigned _originalAutoresizingMask;
	NSMutableArray* _overriddenContentHeightStack;
	char _readyForDisplay;
	char _shouldIgnoreContentScrollViewChanges;
	id<MusicVerticalScrollingContainerItemContextDelegate> _delegate;
	MusicVerticalScrollingContainerItem* _item;

}

@property (assign,nonatomic,__weak) id<MusicVerticalScrollingContainerItemContextDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) MusicVerticalScrollingContainerItem * item;                                        //@synthesize item=_item - In the implementation block
@property (nonatomic,readonly) UIView * itemView; 
@property (getter=isOverridingContentHeight,nonatomic,readonly) char overridingContentHeight; 
-(void)dealloc;
-(void)setDelegate:(id<MusicVerticalScrollingContainerItemContextDelegate>)arg1 ;
-(id<MusicVerticalScrollingContainerItemContextDelegate>)delegate;
-(MusicVerticalScrollingContainerItem *)item;
-(id)initWithItem:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)prepareViewForTearDown;
-(void)_notifyDelegateOfUpdatedContentHeightInContentScrollView;
-(id)_contentScrollView;
-(id)_viewAllowingLoadingFromViewController:(char)arg1 ;
-(void)_updateLayoutOfItemView:(id)arg1 withContentScrollView:(id)arg2 inCell:(id)arg3 withPosition:(unsigned)arg4 containerCollectionView:(id)arg5 ;
-(void)_tearDownContentScrollView;
-(id)_verticallyAdjustableScrollView;
-(char)isOverridingContentHeight;
-(void)beginOverridingContentHeightToValue:(float)arg1 ;
-(float)contentHeightForContentWidth:(float)arg1 withTemporaryParentView:(id)arg2 ;
-(void)endOverridingContentHeight;
-(void)prepareViewForDisplayInCell:(id)arg1 withPosition:(unsigned)arg2 containerCollectionView:(id)arg3 ;
-(void)updateLayoutOfItemViewInCell:(id)arg1 withPosition:(unsigned)arg2 containerCollectionView:(id)arg3 ;
-(UIView *)itemView;
@end

