/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicProductMainViewController.h>
#import <FuseUI/MusicMediaPickerDelegate.h>

@class UIImage, MusicProductDescription, NSNumber, NSString;

@interface MusicPlaylistProductMainViewController : MusicProductMainViewController <MusicMediaPickerDelegate> {

	UIImage* _editedPlaylistArtworkImage;
	MusicProductDescription* _editedPlaylistDescription;
	NSNumber* _editedPlaylistPublicState;
	NSString* _editedPlaylistTitle;
	char _forPlaylistCreation;

}

@property (assign,nonatomic,__weak) id<MusicPlaylistProductMainViewControllerDelegate> delegate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)viewDidLoad;
-(void)configureProductAdditionalMetadataViewController:(id)arg1 ;
-(id)loadProductHeaderLockupContentDescriptor;
-(id)loadProductTracklistTableViewConfigurationWithTracklistEntityProvider:(id)arg1 ;
-(void)toggleProductLikedWithContainerEntityValueContext:(id)arg1 ;
-(void)updateProductHeaderLockupLikedStateWithContainerEntityValueContext:(id)arg1 ;
-(id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(int)arg4 forPlaylistCreation:(char)arg5 ;
-(void)setEditedPlaylistArtworkImage:(id)arg1 ;
-(void)cancelEditing;
-(id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(int)arg4 ;
-(void)_updateEditableComponents;
-(void)_resetAdditionalMedatataViewController:(id)arg1 ;
-(void)commitEditingWithTracklistEntityProviderChangeRecords:(id)arg1 ;
-(void)_setEditedValue:(id)arg1 forProperty:(id)arg2 onPlaylist:(id)arg3 withSuccessfullyEditedPropertiesAccumulatorDictionary:(id)arg4 ;
-(char)_applyInsertChangeRecords:(id)arg1 toPlaylist:(id)arg2 ;
-(char)_applyMoveChangeRecord:(id)arg1 toPlaylist:(id)arg2 ;
-(char)_applyDeleteChangeRecord:(id)arg1 toPlaylist:(id)arg2 ;
-(void)mediaPickerNavigationController:(id)arg1 didFinishWithSelectedEntities:(id)arg2 ;
-(void)productHeaderLockupViewDidSelectAddSongsButton:(id)arg1 ;
-(void)productHeaderLockupView:(id)arg1 didSelectCameraButton:(id)arg2 ;
-(void)productHeaderLockupViewDidSelectShareButton:(id)arg1 ;
-(void)productHeaderLockupViewDidUpdateEditableText:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidSelectAddSongsButton:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidUpdateProductDescription:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidUpdatePublicSwitchState:(id)arg1 ;
@end

