/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:38 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicMediaProductSplitMainViewController.h>
#import <FuseUI/MusicMediaPickerDelegate.h>

@class NSString, MusicProductDescription, NSNumber;

@interface MusicMediaPlaylistSplitMainViewController : MusicMediaProductSplitMainViewController <MusicMediaPickerDelegate> {

	NSString* _curatorStoreID;
	MusicProductDescription* _editedPlaylistDescription;
	NSNumber* _editedPlaylistPublicState;
	NSNumber* _editedPlaylistVisibleState;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setEditedContentArtworkImage:(id)arg1 ;
-(void)_updateEditableComponents;
-(void)_setEditedValue:(id)arg1 forProperty:(id)arg2 onPlaylist:(id)arg3 withSuccessfullyEditedPropertiesAccumulatorDictionary:(id)arg4 ;
-(char)_applyInsertChangeRecords:(id)arg1 toPlaylist:(id)arg2 ;
-(char)_applyMoveChangeRecord:(id)arg1 toPlaylist:(id)arg2 ;
-(char)_applyDeleteChangeRecord:(id)arg1 toPlaylist:(id)arg2 ;
-(void)mediaPickerNavigationController:(id)arg1 didFinishWithSelectedEntities:(id)arg2 ;
-(void)productAdditionalMetadataViewControllerDidSelectAddSongsButton:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidUpdateProductDescription:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidUpdatePublicSwitchState:(id)arg1 ;
-(void)setEditedContentTitle:(id)arg1 ;
-(void)_configureProductAdditionalMetadataViewController:(id)arg1 ;
-(id)_loadProductTracklistTableViewConfigurationWithTracklistEntityProvider:(id)arg1 ;
-(void)productAdditionalMetadataViewControllerDidUpdateVisibleSwitchState:(id)arg1 ;
-(char)productAdditionalMetadataViewControllerShouldDeferContentHeightAnimationUpdates:(id)arg1 ;
-(id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(int)arg4 forContentCreation:(char)arg5 ;
-(id)initWithContainerEntityProvider:(id)arg1 tracklistEntityProvider:(id)arg2 clientContext:(id)arg3 presentationSource:(int)arg4 forContentCreation:(char)arg5 curatorStoreID:(id)arg6 ;
-(void)_commitEditingWithTracklistEntityProviderChangeRecords:(id)arg1 ;
-(char)_isCuratorPlaylist;
-(void)_resetAdditionalMetadataViewController:(id)arg1 ;
@end

