/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:31 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ScreenReaderOutputServer.framework/ScreenReaderOutputServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SCROServerDelegate;
#import <ScreenReaderOutputServer/ScreenReaderOutputServer-Structs.h>
@class NSLock;

@interface SCROServer : NSObject {

	NSLock* _contentLock;
	id<SCROServerDelegate> _delegate;
	CFRunLoopSourceRef _serverSource;
	CFRunLoopSourceRef _deathSource;
	CFRunLoopTimerRef _deathTimer;
	unsigned _serverPort;
	unsigned _deathPort;
	long _clientCount;
	char _isRegisteredWithMach;

}
+(void)initialize;
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)sharedServer;
-(id)retain;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)autorelease;
-(unsigned)retainCount;
-(id)delegate;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CFRunLoopSourceRef)serverSource;
-(void)unregisterWithMach;
-(long)_clientCount;
-(long)_incrementClientCount;
-(void)_setClientCount:(long)arg1 ;
-(CFRunLoopTimerRef)_deathTimer;
-(int)_registerForNotificationOnDeathPort:(unsigned)arg1 ;
-(char)isRegisteredWithMach;
-(char)registerWithMach;
-(oneway void)release;
@end

