/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:00 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <HealthKitUI/HealthKitUI-Structs.h>
#import <UIKit/UITextField.h>

@interface HKCaretOptionalTextField : UITextField {

	char _allowsSelection;

}

@property (assign,nonatomic) char allowsSelection;              //@synthesize allowsSelection=_allowsSelection - In the implementation block
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)setAllowsSelection:(char)arg1 ;
-(char)allowsSelection;
-(CGRect)caretRectForPosition:(id)arg1 ;
@end

