/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CalendarMessageUIProxy : NSObject
+(Class)ComposeRecipientViewClass;
+(Class)SearchShadowViewClass;
+(Class)CalendarComposeRecipientClass;
+(Class)RecipientTableViewCellClass;
+(Class)MailComposeRecipientClass;
+(Class)MFMessageComposeViewControllerClass;
+(Class)MFMailComposeViewControllerClass;
+(Class)MFContactsSearchResultsModelClass;
+(Class)MFContactsSearchManagerClass;
@end

