/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <EventKitUI/EKEventEditItem.h>

@interface EKEventPrivacyLevelInlineEditItem : EKEventEditItem {

	char _originalSwitchState;
	char _currentSwitchState;

}
-(id)cellForSubitemAtIndex:(unsigned)arg1 ;
-(char)isInline;
-(char)saveAndDismissWithForce:(char)arg1 ;
-(void)refreshFromCalendarItemAndStore;
-(char)canBeConfiguredForCalendarConstraints:(id)arg1 ;
-(char)requiresReconfigurationOnCommit;
-(char)forceTableReloadOnCommit;
-(char)shouldAppearWithVisibility:(int)arg1 ;
-(float)footerHeightForWidth:(float)arg1 ;
-(void)_switchChanged:(id)arg1 ;
-(id)footerTitle;
@end

