/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class CalPreferences;

@interface EKUIDebugPreferences : NSObject {

	CalPreferences* _preferences;

}

@property (assign,nonatomic) char showInviteesAndMoreRegion; 
@property (assign,nonatomic) char verifyIntegrityOfAvailabilityTimeSearchTimelines; 
+(id)shared;
-(char)showInviteesAndMoreRegion;
-(void)setShowInviteesAndMoreRegion:(char)arg1 ;
-(char)verifyIntegrityOfAvailabilityTimeSearchTimelines;
-(void)setVerifyIntegrityOfAvailabilityTimeSearchTimelines:(char)arg1 ;
-(id)init;
@end

