/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <EventKitUI/EventKitUI-Structs.h>
#import <EventKitUI/OccurrenceCacheDataSource.h>

@class EKOccurrenceCacheSearch, NSMutableArray;

@interface OccurrenceCacheSearchDataSource : OccurrenceCacheDataSource {

	EKOccurrenceCacheSearch* _search;
	NSMutableArray* _processingCachedDays;
	opaque_pthread_mutex_t _resultsLock;

}
-(void)stopSearching;
-(void)searchWithTerm:(id)arg1 ;
-(char)supportsFakeTodaySection;
-(int)countOfOccurrencesAtDayIndex:(int)arg1 ;
-(id)initWithEventStore:(id)arg1 calendars:(id)arg2 ;
-(void)invalidateCachedOccurrences;
-(id)_cachedDays;
-(char)supportsInvitations;
-(void)_setCachedDaysAndNotify:(id)arg1 ;
-(void)dealloc;
-(void)invalidate;
@end

