/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:30 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FactoryServicesConnectionMobile.framework/FactoryServicesConnectionMobile
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary;

@interface FactoryServiceConnectionHelper : NSObject {

	NSDictionary* _activeServiceConnectionList;

}

@property (retain) NSDictionary * activeServiceConnectionList;              //@synthesize activeServiceConnectionList=_activeServiceConnectionList - In the implementation block
+(id)createErrorDictionaryWithErrorCode:(int)arg1 andErrMsg:(id)arg2 ;
-(NSDictionary *)activeServiceConnectionList;
-(void)setActiveServiceConnectionList:(NSDictionary *)arg1 ;
@end

