/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:13 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol RCCurrentRecordingViewControllerDelegate <NSObject>
@required
-(void)currentRecordingViewControllerRecordingDidEnd:(id)arg1;
-(void)currentRecordingViewController:(id)arg1 didChangeAVState:(id)arg2;
-(void)currentRecordingViewController:(id)arg1 didDeterminteAvailability:(char)arg2;

@end

