/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:06 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/PowerlogFullOperators.framework/PowerlogFullOperators
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PowerlogCore/PLService.h>

@class NSMutableDictionary;

@interface PLSmartPLService : PLService {

	NSMutableDictionary* _smartPLHelpers;

}

@property (retain) NSMutableDictionary * smartPLHelpers;              //@synthesize smartPLHelpers=_smartPLHelpers - In the implementation block
+(void)load;
+(id)entryEventPointDefinitionSmartTrigger;
+(id)entryEventPointDefinitions;
-(id)init;
-(NSMutableDictionary *)smartPLHelpers;
-(void)logEventPointSmartPLFiredFromAuxilary:(Class)arg1 withReason:(id)arg2 ;
-(void)setSmartPLHelpers:(NSMutableDictionary *)arg1 ;
-(void)initOperatorDependancies;
@end

