/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:00 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/___UIRemoteDictionaryViewControllerAccessibility_super.h>

@interface _UIRemoteDictionaryViewControllerAccessibility : ___UIRemoteDictionaryViewControllerAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
@end

