/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:57 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/__UIFieldEditorAccessibility_super.h>

@interface UIFieldEditorAccessibility : __UIFieldEditorAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(void)insertText:(id)arg1 ;
-(char)isAccessibilityElement;
@end

