/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:59 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/__UISplitViewControllerAccessibility_super.h>

@interface UISplitViewControllerAccessibility : __UISplitViewControllerAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(id)_accessibilitySpeakThisViewController;
-(void)_accessibilityLoadAccessibilityInformation;
-(void)_axApplyDisplayModeLabel;
-(void)_axModalizeViewControllerViews;
-(void)viewDidAppear:(char)arg1 ;
-(void)setViewControllers:(id)arg1 ;
-(void)_loadNewSubviews:(id)arg1 ;
-(void)_updateDisplayModeButtonItem;
-(id)displayModeButtonItem;
@end

