/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:58 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/__UIViewAccessibility_super.h>

@interface UIViewAccessibility : __UIViewAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(id)_accessibilityTitleForSystemTag:(int)arg1 ;
-(id)_accessibilityHitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(id)_accessibilityObscuredScreenAllowedViews;
-(id)_axSubviews;
-(id)_accessibilityUserTestingChildren;
-(id)_accessibilityRetrieveLabelFromTableViewCell;
-(id)__accessibilityHitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(id)_accessibilityRetrieveIvarText;
-(char)_accessibilityAvoidsMockViewContainers;
-(char)_accessibilityOnlyComparesByXAxis;
-(id)_accessibilityViewController;
-(char)_accessibilityServesAsContainingParentForOrdering;
-(CGRect)_accessibilityFrameForView:(id)arg1 ;
-(char)_accessibilityObscuredScreenAllowsView:(id)arg1 ;
-(char)_accessibilityPointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(char)_accessibilityBlocksInteraction;
-(id)_accessibilityHitTestSubviews;
-(char)_accessibilityIsIgnored;
-(CGSize)_mainScreenSizeForCurrentOrientation;
-(char)_accessibilityModalViewBlocksView:(id)arg1 blockerView:(id*)arg2 ;
-(id)_accessibilityCheckForAllowedModalView:(CGPoint)arg1 event:(id)arg2 ;
-(char)accessibilityIsWindow;
-(char)_accessibilityShouldHitTestLayers;
-(void)_axPrintSubviews:(int)arg1 string:(id)arg2 ;
-(void)_accessibilityPostNotification:(id)arg1 ;
-(id)_accessibilityAutomaticIdentifier;
-(int)_accessibilityHorizontalSizeClass;
-(int)_accessibilityVerticalSizeClass;
-(id)_superAccessibilityHitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(id)_accessibilityChildVendingParent;
-(id)_accessibilityContainerInDirection:(char)arg1 originalElement:(id)arg2 ;
-(id)_accessibilitySupportGesturesAttributes;
-(id)_accessibilitySortedElementsWithin;
-(id)_axResponderChain;
-(char)_accessibilityIsUserInteractionEnabled;
-(void)_accessibilityFinalize;
-(CGRect)accessibilityFrame;
-(unsigned long long)accessibilityTraits;
-(char)isAccessibilityElement;
-(id)accessibilityContainer;
-(char)accessibilityViewIsModal;
-(char)accessibilityElementsHidden;
-(void)setIsAccessibilityElement:(char)arg1 ;
-(void)setAccessibilityContainer:(id)arg1 ;
-(char)accessibilityElementIsFocused;
@end

