/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:40 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface MFComposeRecipientOriginContext : NSObject {

	NSString* _searchTerm;
	unsigned _resultType;

}

@property (nonatomic,readonly) NSString * searchTerm;              //@synthesize searchTerm=_searchTerm - In the implementation block
@property (nonatomic,readonly) unsigned resultType;                //@synthesize resultType=_resultType - In the implementation block
-(NSString *)searchTerm;
-(void)setSearchTerm:(NSString *)arg1 ;
-(void)dealloc;
-(void)setResultType:(unsigned)arg1 ;
-(unsigned)resultType;
@end

