/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:42 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSMutableDictionary;

@interface MFFontMetricCache : NSObject {

	NSString* _preferredSizeValidationKey;
	NSMutableDictionary* _metricCacheDictionary;

}
+(id)sharedFontMetricCache;
-(id)cachedFont:(/*^block*/id)arg1 forKey:(id)arg2 ;
-(float)cachedFloat:(/*^block*/id)arg1 forKey:(id)arg2 ;
-(char)ensureCacheIsValid;
-(void)_didReceivePreferredFontChangedNotification:(id)arg1 ;
-(void)_invalidateCache;
-(void)dealloc;
-(id)init;
@end

