/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:18 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <RadioUI/ADBannerViewDelegate.h>
#import <RadioUI/ISDialogOperationDelegate.h>

@protocol OS_dispatch_queue;
@class NSObject, MPUJinglePlayActivityReportingController, RUJingleTiltReportingController, RURTCReportingController, ISDialogOperation, MPAVController, MPUReportingPlaybackObserver, NSString;

@interface RURadioAdObserver : NSObject <ADBannerViewDelegate, ISDialogOperationDelegate> {

	NSObject*<OS_dispatch_queue> _accessQueue;
	char _hasDirtyVisualEngagement;
	char _isSlotAcquisitionInProgress;
	int _lastApplicationState;
	MPUJinglePlayActivityReportingController* _jinglePlayActivityReportingController;
	RUJingleTiltReportingController* _jingleTiltReportingController;
	double _minDurationToCountAsPlayed;
	int _policyEngineEnabledCount;
	RURTCReportingController* _RTCReportingController;
	double _skipThreshold;
	ISDialogOperation* _slotAcquisitionDialogOperation;
	int _visualEngagementCount;
	char _visuallyEngaged;
	MPAVController* _player;
	MPUReportingPlaybackObserver* _reportingPlaybackObserver;
	unsigned _numberOfSkippedTracks;

}

@property (nonatomic,retain) MPUJinglePlayActivityReportingController * jinglePlayActivityReportingController;              //@synthesize jinglePlayActivityReportingController=_jinglePlayActivityReportingController - In the implementation block
@property (nonatomic,retain) RUJingleTiltReportingController * jingleTiltReportingController;                               //@synthesize jingleTiltReportingController=_jingleTiltReportingController - In the implementation block
@property (nonatomic,retain) MPAVController * player;                                                                       //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) MPUReportingPlaybackObserver * reportingPlaybackObserver;                                      //@synthesize reportingPlaybackObserver=_reportingPlaybackObserver - In the implementation block
@property (nonatomic,retain) RURTCReportingController * RTCReportingController;                                             //@synthesize RTCReportingController=_RTCReportingController - In the implementation block
@property (getter=isVisuallyEngaged,nonatomic,readonly) char visuallyEngaged;                                               //@synthesize visuallyEngaged=_visuallyEngaged - In the implementation block
@property (nonatomic,readonly) unsigned numberOfSkippedTracks;                                                              //@synthesize numberOfSkippedTracks=_numberOfSkippedTracks - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedAdObserver;
-(void)_playbackStateDidChangeNotification:(id)arg1 ;
-(void)_bufferingStateDidChangeNotification:(id)arg1 ;
-(void)_itemChangedNotification:(id)arg1 ;
-(void)_applicationDidBecomeActiveNotification:(id)arg1 ;
-(void)_unregisterForPlayerNotifications;
-(void)_registerForPlayerNotifications;
-(void)_itemDidFinishLoadingNotification:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)endVisualEngagement;
-(void)beginVisualEngagement;
-(void)_itemWillChangeNotification:(id)arg1 ;
-(void)_applicationWillResignActiveNotification:(id)arg1 ;
-(void)getHistoryWithRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)historyDidEndPlayingAdTrack:(id)arg1 withItem:(id)arg2 ;
-(void)historyDidBeginPlayingAdTrack:(id)arg1 withItem:(id)arg2 ;
-(void)_storeBagDidLoadNotification:(id)arg1 ;
-(void)beginEnablingPolicyEngine;
-(void)attemptSlotAcquisition;
-(void)endEnablingPolicyEngine;
-(void)requestAdsForSlot:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)_loadMinDurationToCountAsPlayedFromURLBag;
-(id)_adPolicyEngine;
-(void)_heartbeatChangedNotification:(id)arg1 ;
-(void)_radioStreamTrackAVItemDidReceiveTimedMetadataPingsNotification:(id)arg1 ;
-(void)_updateWithStoreBag:(id)arg1 ;
-(void)_attemptSlotAcquisitionWithAdditionalBodyParameters:(id)arg1 ;
-(void)_scheduleUpdateVisualEngagement;
-(RURTCReportingController *)RTCReportingController;
-(void)_clearAssetCacheForItem:(id)arg1 ;
-(void)optimalTransmissionWindowDidOpen;
-(void)_itemAssetLoadedDidChangeNotification:(id)arg1 ;
-(void)_handleSkipForChangedItem:(id)arg1 didChangeStation:(char)arg2 ;
-(void)_reportPlaybackEndedForAdTrack:(id)arg1 withItem:(id)arg2 ;
-(char)_isPolicyEngineEnabled;
-(void)_beginEnablingPolicyEngine;
-(void)__scheduleUpdateVisualEngagement;
-(void)didTransitionItemForBan:(id)arg1 ;
-(id)_playActivityFeedEventsForPendingPlayActivityEvents:(id)arg1 ;
-(void)willTransitionItemForBan:(id)arg1 ;
-(void)_getCurrentTime:(double*)arg1 duration:(double*)arg2 wasSkipped:(char*)arg3 didAssetFailToLoad:(char*)arg4 forItem:(id)arg5 ;
-(void)_updateVisualEngagement;
-(void)operation:(id)arg1 selectedButton:(id)arg2 ;
-(void)getTracksWithRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)heartbeatTokenReturningError:(id*)arg1 ;
-(void)noteDidEnterStation:(id)arg1 ;
-(MPUJinglePlayActivityReportingController *)jinglePlayActivityReportingController;
-(void)setJinglePlayActivityReportingController:(MPUJinglePlayActivityReportingController *)arg1 ;
-(RUJingleTiltReportingController *)jingleTiltReportingController;
-(void)setJingleTiltReportingController:(RUJingleTiltReportingController *)arg1 ;
-(MPUReportingPlaybackObserver *)reportingPlaybackObserver;
-(void)setReportingPlaybackObserver:(MPUReportingPlaybackObserver *)arg1 ;
-(void)setRTCReportingController:(RURTCReportingController *)arg1 ;
-(char)isVisuallyEngaged;
-(unsigned)numberOfSkippedTracks;
-(void)setPlayer:(MPAVController *)arg1 ;
-(MPAVController *)player;
@end

