/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:17 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSData;

@interface RURadioStreamPing : NSObject {

	int _type;
	NSData* _value;
	double _timestamp;

}

@property (nonatomic,readonly) double timestamp;                 //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) int type;                         //@synthesize type=_type - In the implementation block
@property (nonatomic,copy,readonly) NSData * value;              //@synthesize value=_value - In the implementation block
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(double)timestamp;
-(int)type;
-(NSData *)value;
-(id)initWithType:(int)arg1 value:(id)arg2 timestamp:(double)arg3 ;
@end

