/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:56 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/PreferencesFramework.axbundle/PreferencesFramework
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PreferencesFramework/__PSSegmentableSliderAccessibility_super.h>

@interface PSSegmentableSliderAccessibility : __PSSegmentableSliderAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(float)_accessibilityIncreaseAmount:(char)arg1 ;
@end

