/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:50 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <GeoServices/GeoServices-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <GeoServices/NSCopying.h>

@class NSMutableArray;

@interface GEONameInfoList : PBCodable <NSCopying> {

	NSMutableArray* _nameInfos;

}

@property (nonatomic,retain) NSMutableArray * nameInfos;              //@synthesize nameInfos=_nameInfos - In the implementation block
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(NSMutableArray *)nameInfos;
-(void)setNameInfos:(NSMutableArray *)arg1 ;
-(void)addNameInfo:(id)arg1 ;
-(unsigned)nameInfosCount;
-(void)clearNameInfos;
-(id)nameInfoAtIndex:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
@end

