/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:53 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <GeoServices/GeoServices-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <GeoServices/NSCopying.h>

@class PBUnknownFields, GEOURLRouteHandle, NSMutableArray;

@interface GEOStorageRouteRequestStorage : PBCodable <NSCopying> {

	PBUnknownFields* _unknownFields;
	GEOURLRouteHandle* _routeHandle;
	int _transportType;
	NSMutableArray* _waypoints;
	SCD_Struct_GE5 _has;

}

@property (nonatomic,retain) NSMutableArray * waypoints;                     //@synthesize waypoints=_waypoints - In the implementation block
@property (assign,nonatomic) char hasTransportType; 
@property (assign,nonatomic) int transportType;                              //@synthesize transportType=_transportType - In the implementation block
@property (nonatomic,readonly) char hasRouteHandle; 
@property (nonatomic,retain) GEOURLRouteHandle * routeHandle;                //@synthesize routeHandle=_routeHandle - In the implementation block
@property (nonatomic,readonly) PBUnknownFields * unknownFields; 
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)setRouteHandle:(GEOURLRouteHandle *)arg1 ;
-(char)hasRouteHandle;
-(GEOURLRouteHandle *)routeHandle;
-(void)setTransportType:(int)arg1 ;
-(char)hasTransportType;
-(PBUnknownFields *)unknownFields;
-(void)setHasTransportType:(char)arg1 ;
-(void)setWaypoints:(NSMutableArray *)arg1 ;
-(void)addWaypoints:(id)arg1 ;
-(unsigned)waypointsCount;
-(void)clearWaypoints;
-(id)waypointsAtIndex:(unsigned)arg1 ;
-(NSMutableArray *)waypoints;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(int)transportType;
@end

