/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:22 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/MediaSocial.framework/MediaSocial
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaSocial/MediaSocial-Structs.h>
#import <StoreKitUI/SKUIViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITextFieldDelegate.h>

@class MSCLAccountStore, MSCLSettingsTextFieldTableViewCell, MSCLSocialService, MSCLSettingsTableViewCell, UITableView, NSString;

@interface MSCLSetupAccountViewController : SKUIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {

	MSCLAccountStore* _accountStore;
	char _isVerifying;
	MSCLSettingsTextFieldTableViewCell* _passwordCell;
	MSCLSocialService* _service;
	MSCLSettingsTableViewCell* _signInButtonCell;
	UITableView* _tableView;
	MSCLSettingsTextFieldTableViewCell* _userNameCell;

}

@property (nonatomic,readonly) MSCLAccountStore * accountStore;              //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,readonly) MSCLSocialService * service;                  //@synthesize service=_service - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(char)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(void)loadView;
-(char)textFieldShouldReturn:(id)arg1 ;
-(MSCLAccountStore *)accountStore;
-(MSCLSocialService *)service;
-(void)_setDefaultOptionsForTextField:(id)arg1 ;
-(void)_textFieldDidChangeNotification:(id)arg1 ;
-(int)_userNameKeyboardType;
-(id)_userNamePlaceholder;
-(char)_textFieldsHaveValues;
-(void)_signIn;
-(void)_setVerifying:(char)arg1 ;
-(void)_finishSignInWithAccount:(id)arg1 error:(id)arg2 ;
-(id)initWithService:(id)arg1 accountStore:(id)arg2 ;
@end

