/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:31 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SPDomainManager : NSObject
+(id)defaultManager;
-(void)registerApplication:(id)arg1 withCategories:(id)arg2 ;
-(void)notifyIndexer;
-(void)_removeAllDomainsForDisplayIdentifier:(id)arg1 ;
-(void)applicationWasUninstalled:(id)arg1 ;
@end

