/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuartzCore/QuartzCore-Structs.h>
#import <QuartzCore/CALayer.h>
#import <QuartzCore/EAGLDrawable.h>

@class NSDictionary;

@interface CAEAGLLayer : CALayer <EAGLDrawable> {

	CAEAGLNativeWindow* _win;

}

@property (readonly) EAGLNativeWindowObject* nativeWindow; 
@property (getter=isAsynchronous) char asynchronous; 
@property (copy) NSDictionary * drawableProperties; 
+(id)defaultValueForKey:(id)arg1 ;
+(char)CA_automaticallyNotifiesObservers:(Class)arg1 ;
-(char)isAsynchronous;
-(void)layerDidBecomeVisible:(char)arg1 ;
-(char)shouldArchiveValueForKey:(id)arg1 ;
-(char)_deferrsDidBecomeVisiblePostCommit;
-(void)_didCommitLayer:(Transaction*)arg1 ;
-(EAGLNativeWindowObject*)nativeWindow;
-(void)discardContents;
-(void)dealloc;
-(void)didChangeValueForKey:(id)arg1 ;
-(void)_display;
-(NSDictionary *)drawableProperties;
-(void)setDrawableProperties:(NSDictionary *)arg1 ;
-(void)setAsynchronous:(char)arg1 ;
@end

