/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BulletinBoard/BBAction.h>

@interface BBLaunchAction : BBAction
+(id)launchActionWithURL:(id)arg1 callblock:(/*^block*/id)arg2 ;
+(id)launchActionWithBundleID:(id)arg1 callblock:(/*^block*/id)arg2 ;
@end

