/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:46 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <Foundation/NSProxy.h>
#import <UIKit/NSCopying.h>

@interface _UIActivityPlaceholderItemProxy : NSProxy <NSCopying> {

	id _placeholderItem;

}
-(Class)class;
-(void)dealloc;
-(char)respondsToSelector:(SEL)arg1 ;
-(char)isEqual:(id)arg1 ;
-(char)isProxy;
-(unsigned)hash;
-(Class)superclass;
-(id)description;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(id)initWithPlaceholderItem:(id)arg1 ;
@end

