/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:53 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>

@interface _UIDictationPrivacySheetController : UINavigationController {

	/*^block*/id _dismissHandler;

}

@property (copy) id dismissHandler;              //@synthesize dismissHandler=_dismissHandler - In the implementation block
+(id)controllerWithDismissHandler:(/*^block*/id)arg1 ;
-(void)dismiss;
-(id)initWithHandler:(/*^block*/id)arg1 ;
-(void)setDismissHandler:(id)arg1 ;
-(id)dismissHandler;
@end

