/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:02 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIFoundation/NSTextAttachment.h>

@class NSDictionary;

@interface _UIDictationAttachment : NSTextAttachment {

	NSDictionary* _typingAttributesBeforeInsertion;
	NSRange _attachmentRange;

}

@property (assign,nonatomic) NSRange attachmentRange;                                   //@synthesize attachmentRange=_attachmentRange - In the implementation block
@property (nonatomic,copy) NSDictionary * typingAttributesBeforeInsertion;              //@synthesize typingAttributesBeforeInsertion=_typingAttributesBeforeInsertion - In the implementation block
-(void)dealloc;
-(NSRange)attachmentRange;
-(void)setAttachmentRange:(NSRange)arg1 ;
-(NSDictionary *)typingAttributesBeforeInsertion;
-(void)setTypingAttributesBeforeInsertion:(NSDictionary *)arg1 ;
@end

