/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSArray, NSURL;


@protocol _UIDocumentPickerServiceViewController <NSObject>
@property (nonatomic,copy,readonly) NSArray * pickableTypes; 
@property (nonatomic,readonly) unsigned pickerMode; 
@property (nonatomic,copy,readonly) NSURL * uploadURL; 
@property (assign,nonatomic) int sortOrder; 
@property (assign,nonatomic) int displayMode; 
@required
-(NSURL *)uploadURL;
-(void)setSortOrder:(int)arg1;
-(NSArray *)pickableTypes;
-(unsigned)pickerMode;
-(int)sortOrder;
-(int)displayMode;
-(void)setupNavigationItemForPicker:(id)arg1 isRoot:(char)arg2;
-(void)dismissWithURL:(id)arg1 forBundleIdentifier:(id)arg2;
-(char)shouldShowSearch;
-(void)setDisplayMode:(int)arg1;

@end

