/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:49 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UIDocumentPickerDocumentTableCell.h>

@class UIImageView;

@interface _UIDocumentPickerDocumentTableContainerCell : _UIDocumentPickerDocumentTableCell {

	UIImageView* _containerIconView;

}

@property (nonatomic,retain) UIImageView * containerIconView;              //@synthesize containerIconView=_containerIconView - In the implementation block
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)prepareForReuse;
-(void)reloadItem:(char)arg1 ;
-(UIImageView *)containerIconView;
-(void)containersChangedWithSnapshot:(id)arg1 differences:(id)arg2 ;
-(void)setContainerIconView:(UIImageView *)arg1 ;
@end

