/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:30 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/_UIModalItemBackgroundView.h>

@class _UIBackdropView, UIImageView;

@interface _UIModalItemAlertBackgroundView : _UIModalItemBackgroundView {

	_UIBackdropView* _effectView;
	UIImageView* _fillingView;

}
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)_gradientImageForBoundsSize:(CGSize)arg1 withInnerColor:(id)arg2 outerColor:(id)arg3 ;
@end

