/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:04 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface _UIObjectPerScreen : NSObject
+(void)removeObject:(id)arg1 ;
+(id)objectOfClass:(Class)arg1 forScreen:(id)arg2 withOptions:(id)arg3 createIfNecessary:(char)arg4 ;
+(void)removeObjectsOfClass:(Class)arg1 ;
+(void)screenDisconnected:(id)arg1 ;
@end

