/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIButton.h>

@interface _UIStepperButton : UIButton {

	char _left;

}

@property (assign,getter=isLeft,nonatomic) char left;              //@synthesize left=_left - In the implementation block
-(CGRect)imageRectForContentRect:(CGRect)arg1 ;
-(char)_shouldDefaultToTemplatesForImageViewBackground:(char)arg1 ;
-(void)setLeft:(char)arg1 ;
-(char)isLeft;
@end

