/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:56 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UIRemoteView.h>

@class _UIRemoteViewController;

@interface _UITextEffectsRemoteView : _UIRemoteView {

	_UIRemoteViewController* _remoteViewController;

}

@property (assign,nonatomic) _UIRemoteViewController * remoteViewController;              //@synthesize remoteViewController=_remoteViewController - In the implementation block
+(char)_requiresWindowTouches;
-(int)textEffectsVisibilityLevel;
-(_UIRemoteViewController *)remoteViewController;
-(void)setRemoteViewController:(_UIRemoteViewController *)arg1 ;
@end

