/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:42 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIKBRenderFactory_Emoji.h>

@interface UIKBRenderFactoryEmoji_iPad_Split : UIKBRenderFactory_Emoji
-(id)backgroundTraitsForKeyplane:(id)arg1 ;
-(id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2 ;
-(id)lightKeycapsFontName;
-(void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4 ;
-(float)emojiInternationalKeySize;
-(CGPoint)emojiInternationalKeyOffset;
-(CGPoint)emojiPopupTextOffset;
-(char)shouldClearBaseDisplayStringForVariants:(id)arg1 ;
-(id)thinKeycapsFontName;
-(float)keyCornerRadius;
@end

