/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:42 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKBRenderFactory.h>

@interface UIKBRenderFactory_Emoji : UIKBRenderFactory
-(id)backgroundTraitsForKeyplane:(id)arg1 ;
-(id)defaultKeyBackgroundColorName;
-(id)controlKeyBackgroundColorName;
-(id)_emojiDefaultControlKeyActiveBackgroundColorGradient;
-(id)_emojiDefaultControlKeyBackgroundColorGradient;
-(id)_emojiSpaceKeyActiveBackgroundColorGradient;
-(id)_emojiSpaceKeyBackgroundColorGradient;
-(id)_emojiCategoryControlKeyActiveTraits;
-(id)_emojiBorderColor;
-(id)_emojiSkinToneDividerColor;
@end

