/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:50 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIKeyboardCandidateBarLayoutDelegate <UICollectionViewDelegate>
@optional
-(void)candidateBarLayoutDidFinishPreparingLayout;

@required
-(CGSize*)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
-(CGSize*)sizeOfDummyItemForCollectionView:(id)arg1 layout:(id)arg2;

@end

