/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:49 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIView.h>

@interface UIKeyboardCornerView : UIView {

	char _leftSide;
	float _radius;

}
-(void)drawRect:(CGRect)arg1 ;
-(int)textEffectsVisibilityLevel;
-(id)initWithFrame:(CGRect)arg1 left:(char)arg2 ;
@end

