/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:41 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIUserNotificationCategory.h>

@class NSString;

@interface UIMutableUserNotificationCategory : UIUserNotificationCategory {

	NSString* identifier;

}

@property (nonatomic,copy) NSString * identifier; 
-(NSString *)identifier;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setActions:(id)arg1 forContext:(unsigned)arg2 ;
@end

