/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:59 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIStatusBarIndicatorItemView.h>

@interface UIStatusBarQuietModeItemView : UIStatusBarIndicatorItemView {

	char _hideForAction;
	char _registeredForNotifications;
	char _inactive;

}
-(void)dealloc;
-(void)animationDidStop:(id)arg1 finished:(char)arg2 ;
-(void)setVisible:(char)arg1 ;
-(char)updateForNewData:(id)arg1 actions:(int)arg2 ;
-(void)setVisible:(char)arg1 frame:(CGRect)arg2 duration:(double)arg3 ;
-(void)_triggerAction:(id)arg1 ;
-(float)_visibleAlpha;
@end

