/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:04 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/NSCopying.h>
#import <UIKit/NSSecureCoding.h>

@class NSDictionary;

@interface UITraitCollection : NSObject <NSCopying, NSSecureCoding> {

	SCD_Struct_UI92 _builtinTraits;
	NSDictionary* _clientDefinedTraits;

}

@property (nonatomic,readonly) char MPU_hasCompactHeight; 
@property (nonatomic,readonly) char MPU_hasCompactWidth; 
@property (nonatomic,readonly) char MPU_hasRegularHeight; 
@property (nonatomic,readonly) char MPU_hasRegularWidth; 
@property (nonatomic,readonly) int userInterfaceIdiom; 
@property (nonatomic,readonly) float displayScale; 
@property (nonatomic,readonly) int horizontalSizeClass; 
@property (nonatomic,readonly) int verticalSizeClass; 
+(char)supportsSecureCoding;
+(id)traitCollectionWithDisplayScale:(float)arg1 ;
+(id)traitCollectionWithHorizontalSizeClass:(int)arg1 ;
+(id)traitCollectionWithVerticalSizeClass:(int)arg1 ;
+(id)traitCollectionWithTraitsFromCollections:(id)arg1 ;
+(id)_emptyTraitCollection;
+(id)traitCollectionWithUserInterfaceIdiom:(int)arg1 ;
+(id)traitCollectionWithInteractionModel:(unsigned)arg1 ;
+(id)traitCollectionWithTouchLevel:(int)arg1 ;
+(id)_traitCollectionWithValue:(id)arg1 forTraitNamed:(id)arg2 ;
-(char)MPU_hasRegularWidth;
-(char)MPU_hasRegularHeight;
-(char)MPU_hasCompactHeight;
-(char)MPU_hasCompactWidth;
-(void)dealloc;
-(int)userInterfaceIdiom;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(int)verticalSizeClass;
-(int)horizontalSizeClass;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)_initWithBuiltinTraitStorage:(SCD_Struct_UI92*)arg1 clientDefinedTraits:(id)arg2 ;
-(float)displayScale;
-(char)containsTraitsInCollection:(id)arg1 ;
-(unsigned)interactionModel;
-(id)_valueForTraitNamed:(id)arg1 ;
-(int)_compare:(id)arg1 ;
-(id)_namedImageDescription;
-(char)_matchesIntersectionWithTraitCollection:(id)arg1 ;
-(int)touchLevel;
@end

