/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:38:50 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <UIKit/UIKit-Structs.h>
@class DOMNode;

@interface UIWebOverflowScrollInfo : NSObject {

	char _isUserScroll;
	DOMNode* _node;
	CGPoint _offset;

}

@property (nonatomic,retain) DOMNode * node;                 //@synthesize node=_node - In the implementation block
@property (assign,nonatomic) CGPoint offset;                 //@synthesize offset=_offset - In the implementation block
@property (assign,nonatomic) char isUserScroll;              //@synthesize isUserScroll=_isUserScroll - In the implementation block
-(void)dealloc;
-(void)setOffset:(CGPoint)arg1 ;
-(CGPoint)offset;
-(DOMNode *)node;
-(id)initWithNode:(id)arg1 offset:(CGPoint)arg2 isUserScroll:(char)arg3 ;
-(char)coalesceScrollForNode:(id)arg1 offset:(CGPoint)arg2 isUserScroll:(char)arg3 ;
-(void)setNode:(DOMNode *)arg1 ;
-(char)isUserScroll;
-(void)setIsUserScroll:(char)arg1 ;
@end

