/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:41 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/CHDAxis.h>

@interface CHDCategoryAxis : CHDAxis {

	BOOL mAutomatic;
	BOOL mNoMultipleLevelLabel;
	int mLabelAlignment;
	long mLabelFrequency;
	BOOL mLabelFrequencyAutomatic;
	BOOL mShowSeriesNames;

}
-(id)initWithResources:(id)arg1 ;
-(void)setLabelFrequency:(long)arg1 ;
-(long)labelFrequency;
-(void)adjustAxisPositionForHorizontalChart;
-(BOOL)isAutomatic;
-(void)setAutomatic:(BOOL)arg1 ;
-(BOOL)isNoMultipleLabellevel;
-(void)setNoMultipleLevelLabel:(BOOL)arg1 ;
-(int)labelAlignment;
-(void)setLabelAlignment:(int)arg1 ;
-(void)setShowSeriesLabels:(BOOL)arg1 ;
-(BOOL)showSeriesLabels;
-(BOOL)isLabelFrequencyAutomatic;
@end

