/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class ECIntTwoIntKeyDictionary;

@interface ECIntToTwoIntKeyCache : NSObject {

	ECIntTwoIntKeyDictionary* mCache;

}
-(void)dealloc;
-(id)init;
-(void)setObject:(unsigned)arg1 forKey1:(unsigned)arg2 key2:(unsigned)arg3 ;
-(char)integerIsPresentForKey1:(unsigned)arg1 key2:(unsigned)arg2 outValue:(unsigned*)arg3 ;
@end

