/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:43 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface EDTokenTree : NSObject
+(id)buildSubtreeAtIndex:(unsigned*)arg1 formula:(id)arg2 ;
+(id)buildSubtree:(unsigned)arg1 formula:(id)arg2 ;
+(unsigned)childCountForToken:(unsigned)arg1 formula:(id)arg2 ;
+(BOOL)isTokenNoOp:(unsigned)arg1 formula:(id)arg2 ;
+(BOOL)isTokenAttrASum:(unsigned short)arg1 ;
@end

