/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/CMMapper.h>

@interface EMSeriesMapper : CMMapper
-(unsigned)markerType;
-(id)values;
-(float)offset;
-(CGColorRef)fillColor;
-(CGColorRef)strokeColor;
-(unsigned)chartType;
-(BOOL)useSecondaryAxis;
-(CGColorRef)markerColor;
-(float)markerWidth;
-(float)strokeWidth;
@end

