/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface OADFontScheme : NSObject {

	NSMutableDictionary* mMajorFont;
	NSMutableDictionary* mMinorFont;

}
+(void)addFontEntry:(id)arg1 script:(id)arg2 typeface:(id)arg3 ;
-(void)dealloc;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(id)description;
-(char)isFontSchemeRef:(id)arg1 ;
-(id)fontForFontSchemeRef:(id)arg1 ;
-(id)majorTypefaceForScript:(id)arg1 ;
-(id)minorTypefaceForScript:(id)arg1 ;
-(unsigned)majorFontCount;
-(id)majorFont;
-(unsigned)minorFontCount;
-(id)minorFont;
@end

