/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/OADBulletSize.h>

@interface OADPointBulletSize : OADBulletSize {

	int mPoints;

}
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)initWithPoints:(int)arg1 ;
-(int)points;
@end

