/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:38 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class OADBaseStyles, OADDefaultProperties;

@interface OADTheme : NSObject {

	OADBaseStyles* mBaseStyles;
	OADDefaultProperties* mShapeDefaults;
	OADDefaultProperties* mLineDefaults;
	OADDefaultProperties* mTextDefaults;

}

@property (nonatomic,retain) OADBaseStyles * baseStyles; 
@property (nonatomic,retain) OADDefaultProperties * shapeDefaults; 
@property (nonatomic,retain) OADDefaultProperties * lineDefaults; 
@property (nonatomic,retain) OADDefaultProperties * textDefaults; 
-(void)dealloc;
-(id)init;
-(OADBaseStyles *)baseStyles;
-(id)addShapeDefaults;
-(id)addLineDefaults;
-(id)addTextDefaults;
-(void)addDefaults;
-(void)setBaseStyles:(OADBaseStyles *)arg1 ;
-(OADDefaultProperties *)shapeDefaults;
-(void)setShapeDefaults:(OADDefaultProperties *)arg1 ;
-(OADDefaultProperties *)lineDefaults;
-(void)setLineDefaults:(OADDefaultProperties *)arg1 ;
-(OADDefaultProperties *)textDefaults;
-(void)setTextDefaults:(OADDefaultProperties *)arg1 ;
@end

