/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:39 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface OAVWriteClient : NSObject
-(void)updateClientAnchorFromOrientedBoundsForDrawable:(id)arg1 state:(id)arg2 ;
-(void)writeClientDataFromDrawable:(id)arg1 toStyle:(id)arg2 state:(id)arg3 ;
-(void)writeClientDataFromDrawable:(id)arg1 toXmlWriter:(id)arg2 state:(id)arg3 ;
-(id)textWrapPointsForDrawable:(id)arg1 state:(id)arg2 ;
@end

