/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:38 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface ODDColorTransform : NSObject {

	NSMutableDictionary* mStyleLabels;

}
-(void)dealloc;
-(id)init;
-(id)labelForName:(id)arg1 ;
-(void)setLabel:(id)arg1 forName:(id)arg2 ;
@end

