/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:38 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface ODDFillColorList : NSObject {

	NSArray* mColors;
	int mHueDirection;
	int mMethod;

}
-(void)dealloc;
-(void)setColors:(id)arg1 ;
-(id)cycleColorAtIndex:(unsigned)arg1 ;
-(id)repeatColorAtIndex:(unsigned)arg1 ;
-(id)spanColorAtIndex:(unsigned)arg1 count:(unsigned)arg2 state:(id)arg3 ;
-(id)colorAtIndex:(unsigned)arg1 count:(unsigned)arg2 state:(id)arg3 ;
-(void)setHueDirection:(int)arg1 ;
-(void)getComponentsForIndex:(unsigned)arg1 hue:(float*)arg2 saturation:(float*)arg3 brightness:(float*)arg4 state:(id)arg5 ;
-(void)setMethod:(int)arg1 ;
@end

