/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:34 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OITSUFlushableObject.h>

@interface OITSUFlushableCachedImage : OITSUFlushableObject {

	CGImageRef _image;
	id _delegate;
	SEL _delegateCreateImageSelector;

}
-(void)dealloc;
-(void)unload;
-(id)initWithDelegate:(id)arg1 createImageSelector:(SEL)arg2 ;
-(char)hasFlushableContent;
-(CGImageRef)newImage;
@end

