/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:46 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class OADDrawable;

@interface PDBuild : NSObject {

	char mIsAnimateBackground;
	OADDrawable* mDrawable;

}
-(void)dealloc;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(id)drawable;
-(void)setDrawable:(id)arg1 ;
-(char)isAnimateBackground;
-(void)setIsAnimateBackground:(char)arg1 ;
@end

