/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/CMStyle.h>

@interface WMStyle : CMStyle
-(void)addCharacterProperties:(id)arg1 ;
-(id)initWithWDStyle:(id)arg1 ;
-(void)cascadeWithStyle:(id)arg1 ;
-(id)initWithWDStyle:(id)arg1 isInTextFrame:(char)arg2 ;
-(void)ResoveInterPropertyDependencies;
-(id)cssStyleString;
-(id)initWithWMStyle:(id)arg1 ;
-(id)initWithWDCharacterProperties:(id)arg1 ;
@end

