/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:56 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UIColor;

@interface SBPieChartSlice : NSObject {

	float _value;
	UIColor* _fillColor;

}

@property (readonly) float value;                             //@synthesize value=_value - In the implementation block
@property (retain,readonly) UIColor * fillColor;              //@synthesize fillColor=_fillColor - In the implementation block
+(id)sliceWithValue:(float)arg1 fillColor:(id)arg2 ;
-(id)initWithValue:(float)arg1 fillColor:(id)arg2 ;
-(void)dealloc;
-(float)value;
-(UIColor *)fillColor;
@end

