/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:49 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBIconListPageControl.h>

@interface SBStarkIconListPageControl : SBIconListPageControl {

	float _scale;

}

@property (assign,nonatomic) float scale;              //@synthesize scale=_scale - In the implementation block
-(id)_iconListIndicatorImage:(char)arg1 ;
-(float)scale;
-(void)setScale:(float)arg1 ;
-(float)_indicatorSpacing;
@end

