/*
* This header is generated by classdump-dyld 0.7
* on Monday, July 6, 2015 at 12:14:51 AM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface SBTodayTableHeaderView : UIView {

	UILabel* _dateLabel;
	UILabel* _lunarDateLabel;
	char _isContentValid;
	CGRect _calculatedDateLabelFrame;
	char _achievedPreferredDateLabelLayout;
	CGSize _sizeThatFitsCalculatedDateLabelFrame;
	CGRect _calculatedLunarDateLabelFrame;
	int _layoutMode;

}

@property (assign,nonatomic) int layoutMode;              //@synthesize layoutMode=_layoutMode - In the implementation block
+(id)defaultLunarDateFont;
+(id)defaultDateFont;
+(float)lunarDateBaselineOffset;
+(id)defaultTextColor;
+(id)defaultBackgroundColor;
-(void)setLayoutMode:(int)arg1 ;
-(void)invalidateContent;
-(void)_updateForContentCategorySizeDidChange;
-(id)dateHeaderOnSingleLine:(char)arg1 ;
-(id)lunarCalendarIdentifier;
-(float)_dateLabelWidthForSize:(CGSize)arg1 layoutMode:(int)arg2 ;
-(char)_dateLabelNeedsLayoutForSize:(CGSize)arg1 ;
-(id)dateHeaderAttributedStringOnSingleLine:(char)arg1 ;
-(char)_isCachedSizeThatFitsValidForSize:(CGSize)arg1 ;
-(CGRect)dateLabelFrameForBounds:(CGRect)arg1 force:(char)arg2 ;
-(char)showsLunarDate;
-(id)lunarDateHeaderString;
-(CGRect)_lunarDateLabelFrameForBounds:(CGRect)arg1 ;
-(void)_layoutLunarDateLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(int)layoutMode;
-(void)_layoutDateLabel;
@end

