/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface MSASCommentCheckOperation : NSObject {

	NSString* _albumGUID;
	NSString* _assetCollectionGUID;

}

@property (nonatomic,retain) NSString * albumGUID;                        //@synthesize albumGUID=_albumGUID - In the implementation block
@property (nonatomic,retain) NSString * assetCollectionGUID;              //@synthesize assetCollectionGUID=_assetCollectionGUID - In the implementation block
-(NSString *)albumGUID;
-(void)setAlbumGUID:(NSString *)arg1 ;
-(void)setAssetCollectionGUID:(NSString *)arg1 ;
-(NSString *)assetCollectionGUID;
@end

