/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MSStreamsProtocolDelegate <NSObject>
@optional
-(void)protocol:(id)arg1 didReceiveRetryAfterDate:(id)arg2;

@end

