/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SiriUI/SiriUISnippetViewController.h>
#import <SiriUI/SiriUIObjectPickerViewControllerDelegate.h>

@class SAABPersonPicker, SiriUIObjectPickerViewController, NSString;

@interface SiriUIPrivatePeoplePickerViewController : SiriUISnippetViewController <SiriUIObjectPickerViewControllerDelegate> {

	SAABPersonPicker* _picker;
	SiriUIObjectPickerViewController* _pickerController;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(float)desiredHeightForWidth:(float)arg1 ;
-(void)loadView;
-(void)_showPicker:(id)arg1 ;
-(id)_pickerController;
-(id)viewControllerForPickerPresentation:(id)arg1 ;
-(void)pickerViewController:(id)arg1 willPresentPicker:(id)arg2 ;
-(void)pickerViewController:(id)arg1 willDismissPicker:(id)arg2 ;
-(void)pickerViewController:(id)arg1 didSelectObject:(id)arg2 fromPicker:(id)arg3 ;
-(id)initWithSnippet:(id)arg1 ;
-(Class)transparentFooterViewClass;
-(void)configureReusableTransparentFooterView:(id)arg1 ;
-(float)desiredHeightForTransparentFooterView;
@end

