/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SiriUI.framework/SiriUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SiriUISnippetPlugin;
@class NSBundle;

@interface SVSSnippetPluginBundle : NSObject {

	NSBundle* _bundle;
	id<SiriUISnippetPlugin> _snippetPlugin;

}

@property (nonatomic,retain) NSBundle * bundle;                                  //@synthesize bundle=_bundle - In the implementation block
@property (nonatomic,retain) id<SiriUISnippetPlugin> snippetPlugin;              //@synthesize snippetPlugin=_snippetPlugin - In the implementation block
+(id)snippetPluginWithBundle:(id)arg1 ;
-(NSBundle *)bundle;
-(void)setBundle:(NSBundle *)arg1 ;
-(id<SiriUISnippetPlugin>)snippetPlugin;
-(void)setSnippetPlugin:(id<SiriUISnippetPlugin>)arg1 ;
@end

