/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:53 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/CameraKit.axbundle/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/__CAMFlipButtonAccessibility_super.h>

@interface CAMFlipButtonAccessibility : __CAMFlipButtonAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
-(id)accessibilityIdentifier;
-(id)accessibilityLabel;
-(id)accessibilityValue;
-(id)accessibilityHint;
@end

