/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:44 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Celestial/Celestial-Structs.h>
@class NSString;

@interface BWDroppedSample : NSObject {

	NSString* _reason;
	SCD_Struct_BW2 _pts;

}

@property (readonly) NSString * reason; 
@property (readonly) SCD_Struct_BW2 pts; 
+(id)newDroppedSampleWithReason:(id)arg1 pts:(SCD_Struct_BW2)arg2 ;
-(void)dealloc;
-(NSString *)reason;
-(SCD_Struct_BW2)pts;
-(id)_initDroppedSampleWithReason:(id)arg1 pts:(SCD_Struct_BW2)arg2 ;
@end

