/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:32 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SUActivityDelegate <NSObject>
@optional
-(char)activity:(id)arg1 canPerformWithActivityItems:(id)arg2;
-(void)activity:(id)arg1 prepareWithActivityItems:(id)arg2;
-(void)performActionForActivity:(id)arg1;

@end

