/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:31 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUItemCellContext.h>

@interface SUMediaItemCellContext : SUItemCellContext {

	float _artworkWidth;
	int _hiddenMediaIconTypes;
	char _itemsHaveArtwork;

}

@property (assign,nonatomic) float artworkWidth;                    //@synthesize artworkWidth=_artworkWidth - In the implementation block
@property (assign,nonatomic) int hiddenMediaIconTypes;              //@synthesize hiddenMediaIconTypes=_hiddenMediaIconTypes - In the implementation block
@property (assign,nonatomic) char itemsHaveArtwork;                 //@synthesize itemsHaveArtwork=_itemsHaveArtwork - In the implementation block
-(id)init;
-(float)artworkWidth;
-(void)setArtworkWidth:(float)arg1 ;
-(void)setHiddenMediaIconTypes:(int)arg1 ;
-(void)setItemsHaveArtwork:(char)arg1 ;
-(int)hiddenMediaIconTypes;
-(char)itemsHaveArtwork;
@end

