/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:30 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptViewController.h>

@class NSArray, NSString;

@interface SUScriptMediaPickerController : SUScriptViewController

@property (assign) char allowsPickingMultipleItems; 
@property (readonly) NSArray * mediaTypes; 
@property (retain) NSString * prompt; 
+(void)initialize;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(char)allowsPickingMultipleItems;
-(void)setAllowsPickingMultipleItems:(char)arg1 ;
-(id)initWithMediaTypes:(id)arg1 ;
-(NSString *)prompt;
-(void)setPrompt:(NSString *)arg1 ;
-(NSArray *)mediaTypes;
-(id)scriptAttributeKeys;
-(id)_className;
-(id)attributeKeys;
-(void)setNativeViewController:(id)arg1 ;
-(id)newNativeViewController;
@end

