/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:33 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUScriptObject.h>

@class SSLookupRequest, NSString;

@interface SUScriptLookupRequest : SUScriptObject {

	SSLookupRequest* _request;

}

@property (retain) id authenticatesIfNeeded; 
@property (copy) NSString * keyProfile; 
@property (assign) int localizationStyle; 
@property (readonly) int localizationStyleDevice; 
@property (readonly) int localizationStyleServer; 
+(void)initialize;
+(id)webScriptNameForSelector:(SEL)arg1 ;
+(id)webScriptNameForKeyName:(id)arg1 ;
-(void)setLocalizationStyle:(int)arg1 ;
-(id)valueForRequestParameter:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setKeyProfile:(NSString *)arg1 ;
-(void)setValue:(id)arg1 forRequestParameter:(id)arg2 ;
-(id)scriptAttributeKeys;
-(id)_className;
-(NSString *)keyProfile;
-(int)localizationStyle;
-(id)authenticatesIfNeeded;
-(void)setAuthenticatesIfNeeded:(id)arg1 ;
-(id)attributeKeys;
-(void)startWithLookupFunction:(id)arg1 ;
-(int)localizationStyleDevice;
-(int)localizationStyleServer;
@end

