/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:31 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUMediaItemCellConfiguration.h>

@interface SUShortLinkCellConfiguration : SUMediaItemCellConfiguration
+(float)rowHeightForContext:(id)arg1 representedObject:(id)arg2 ;
+(id)copyDefaultContext;
-(id)init;
-(id)fontForLabelAtIndex:(unsigned)arg1 ;
-(id)colorForLabelAtIndex:(unsigned)arg1 withModifiers:(unsigned)arg2 ;
-(void)reloadStrings;
-(void)reloadLayoutInformation;
-(id)copyImageDataProvider;
-(char)showContentRating;
@end

