/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:28 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SURotationController.h>

@class SURotationController, SUViewController;

@interface SUStorePageRotationController : SURotationController {

	SURotationController* _childRotationController;
	SUViewController* _childViewController;

}
-(void)dealloc;
-(void)finishRotationFromInterfaceOrientation:(int)arg1 ;
-(void)animateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)prepareToRotateToInterfaceOrientation:(int)arg1 ;
-(id)_childRotationController;
@end

