/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <UIKit/UIView.h>

@class NSDictionary;

@interface CAMHardwareLockIndicatorView : UIView {

	char _focusLocked;
	char _exposureLocked;
	NSDictionary* __indicatorTextAttributes;

}

@property (assign,getter=isFocusLocked,nonatomic) char focusLocked;                    //@synthesize focusLocked=_focusLocked - In the implementation block
@property (assign,getter=isExposureLocked,nonatomic) char exposureLocked;              //@synthesize exposureLocked=_exposureLocked - In the implementation block
@property (nonatomic,readonly) NSDictionary * _indicatorTextAttributes;                //@synthesize _indicatorTextAttributes=__indicatorTextAttributes - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)_updateFromHardwareChange;
-(void)_commonCAMHardwareLockIndicatorViewInitialization;
-(id)_textForCurrentHardwareState;
-(NSDictionary *)_indicatorTextAttributes;
-(CGSize)_roundedSizeOfText:(id)arg1 withAttributes:(id)arg2 ;
-(void)setFocusLocked:(char)arg1 ;
-(void)setExposureLocked:(char)arg1 ;
-(char)isFocusLocked;
-(char)isExposureLocked;
@end

