/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:36 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <CameraKit/CameraKit-Structs.h>
@interface CAMPanoramaCaptureParameters : NSObject {

	double _speed;
	CGRect _cropRectangle;

}

@property (assign,nonatomic) double speed;                      //@synthesize speed=_speed - In the implementation block
@property (assign,nonatomic) CGRect cropRectangle;              //@synthesize cropRectangle=_cropRectangle - In the implementation block
-(void)setSpeed:(double)arg1 ;
-(double)speed;
-(CGRect)cropRectangle;
-(void)setCropRectangle:(CGRect)arg1 ;
@end

