/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <UIKit/UIView.h>

@interface PLCameraIrisAnimationView : UIView {

	char shouldSetupAnimationInDidMoveToWindow;
	id irisAnimationDelegate;
	SEL irisAnimationDidStopSelector;
	double irisAnimationDuration;
	CGPoint irisAnimationPosition;

}

@property (assign,nonatomic) id irisAnimationDelegate; 
@property (assign,nonatomic) SEL irisAnimationDidStopSelector; 
@property (assign,nonatomic) double irisAnimationDuration; 
@property (assign,nonatomic) CGPoint irisAnimationPosition; 
@property (assign,nonatomic) char shouldSetupAnimationInDidMoveToWindow; 
-(void)dealloc;
-(void)didMoveToWindow;
-(void)setIrisAnimationDelegate:(id)arg1 ;
-(void)setIrisAnimationDidStopSelector:(SEL)arg1 ;
-(id)irisAnimationDelegate;
-(SEL)irisAnimationDidStopSelector;
-(double)irisAnimationDuration;
-(CGPoint)irisAnimationPosition;
-(void)setupAnimation;
-(char)shouldSetupAnimationInDidMoveToWindow;
-(void)unpauseIrisAnimation;
-(void)pauseIrisAnimation;
-(void)animateIrisOpen;
-(void)setIrisAnimationDuration:(double)arg1 ;
-(void)setIrisAnimationPosition:(CGPoint)arg1 ;
-(void)setShouldSetupAnimationInDidMoveToWindow:(char)arg1 ;
@end

