/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:30 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface FBApplicationDefaults : NSObject {

	int _interfaceOrientation;
	int _backgroundStyle;
	int _statusBarStyle;
	char _statusBarHidden;
	char _statusBarHiddenWhenVerticallyCompact;

}

@property (assign,nonatomic) int interfaceOrientation;                               //@synthesize interfaceOrientation=_interfaceOrientation - In the implementation block
@property (assign,nonatomic) int statusBarStyle;                                     //@synthesize statusBarStyle=_statusBarStyle - In the implementation block
@property (assign,nonatomic) int backgroundStyle;                                    //@synthesize backgroundStyle=_backgroundStyle - In the implementation block
@property (assign,nonatomic) char statusBarHidden;                                   //@synthesize statusBarHidden=_statusBarHidden - In the implementation block
@property (assign,nonatomic) char statusBarHiddenWhenVerticallyCompact;              //@synthesize statusBarHiddenWhenVerticallyCompact=_statusBarHiddenWhenVerticallyCompact - In the implementation block
-(id)init;
-(int)interfaceOrientation;
-(char)statusBarHidden;
-(int)statusBarStyle;
-(void)setStatusBarStyle:(int)arg1 ;
-(void)setStatusBarHidden:(char)arg1 ;
-(void)setInterfaceOrientation:(int)arg1 ;
-(void)setBackgroundStyle:(int)arg1 ;
-(int)backgroundStyle;
-(char)statusBarHiddenWhenVerticallyCompact;
-(void)setStatusBarHiddenWhenVerticallyCompact:(char)arg1 ;
@end

