/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <SpringBoardUIServices/SBUIEmergencyCallServiceInterface.h>

@class UIColor;

@interface SBUIEmergencyCallServiceViewController : UIViewController <SBUIEmergencyCallServiceInterface> {

	int _backgroundStyle;
	UIColor* _tintColor;

}

@property (assign,nonatomic) int backgroundStyle;                       //@synthesize backgroundStyle=_backgroundStyle - In the implementation block
@property (nonatomic,retain,readonly) UIColor * tintColor;              //@synthesize tintColor=_tintColor - In the implementation block
+(id)_exportedInterface;
+(id)_remoteViewControllerInterface;
-(void)dealloc;
-(UIColor *)tintColor;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)setBackgroundStyle:(int)arg1 ;
-(int)backgroundStyle;
-(void)backgroundStyle:(/*^block*/id)arg1 ;
-(void)noteTintColorForBackgroundStyleChanged:(id)arg1 ;
-(void)noteViewMovedOffscreenTemporarily;
@end

