/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:15 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AVKit.framework/AVKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AVKit/AVKit-Structs.h>
#import <UIKit/UIView.h>

@interface AVPlayerView : UIView {

	int _viewWindowState;

}

@property (nonatomic,readonly) int viewWindowState; 
-(int)viewWindowState;
-(void)_updateViewWindowState;
-(void)didMoveToWindow;
-(void)setFrame:(CGRect)arg1 ;
-(void)willMoveToWindow:(id)arg1 ;
@end

