/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:56 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSHTTPURLResponse, NSString, NSNumber;

@interface SSAuthenticationResponse : NSObject {

	NSDictionary* _responseDictionary;
	int _urlBagType;
	NSHTTPURLResponse* _urlResponse;

}

@property (assign) int URLBagType;                                       //@synthesize urlBagType=_urlBagType - In the implementation block
@property (readonly) NSDictionary * responseDictionary;                  //@synthesize responseDictionary=_responseDictionary - In the implementation block
@property (readonly) NSHTTPURLResponse * URLResponse; 
@property (readonly) NSString * accountName; 
@property (readonly) int accountKind; 
@property (readonly) NSNumber * accountUniqueIdentifier; 
@property (readonly) int availableServiceTypes; 
@property (readonly) NSString * creditsString; 
@property (readonly) int enabledServiceTypes; 
@property (getter=isNewCustomer,readonly) char newCustomer; 
@property (readonly) NSString * storeFrontIdentifier; 
@property (readonly) NSString * token; 
@property (readonly) NSNumber * failureType; 
@property (readonly) int responseType; 
@property (readonly) NSString * userMessage; 
-(NSString *)storeFrontIdentifier;
-(NSHTTPURLResponse *)URLResponse;
-(void)dealloc;
-(NSString *)token;
-(NSString *)userMessage;
-(NSDictionary *)responseDictionary;
-(void)setURLBagType:(int)arg1 ;
-(int)URLBagType;
-(NSString *)accountName;
-(NSString *)creditsString;
-(int)responseType;
-(char)isNewCustomer;
-(int)enabledServiceTypes;
-(int)accountKind;
-(int)availableServiceTypes;
-(id)initWithURLResponse:(id)arg1 dictionary:(id)arg2 ;
-(id)newAccount;
-(NSNumber *)failureType;
-(id)_valueForFirstAvailableKey:(id)arg1 ;
-(NSNumber *)accountUniqueIdentifier;
-(int)_responseTypeForFailureType:(int)arg1 ;
-(int)_responseTypeForErrorNumber:(int)arg1 ;
-(int)_responseTypeForStatusValue:(int)arg1 ;
@end

