/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSNumber, NSURL;

@interface SSVContentLink : NSObject {

	NSString* _categoryName;
	int _contentKind;
	NSNumber* _itemIdentifier;
	NSString* _itemTitle;
	NSString* _providerName;
	NSString* _searchTerm;
	int _targetApplication;

}

@property (assign,nonatomic) int contentKind;                      //@synthesize contentKind=_contentKind - In the implementation block
@property (assign,nonatomic) int targetApplication;                //@synthesize targetApplication=_targetApplication - In the implementation block
@property (nonatomic,readonly) NSURL * URL; 
@property (nonatomic,copy) NSString * categoryName;                //@synthesize categoryName=_categoryName - In the implementation block
@property (nonatomic,copy) NSNumber * itemIdentifier;              //@synthesize itemIdentifier=_itemIdentifier - In the implementation block
@property (nonatomic,copy) NSString * itemTitle;                   //@synthesize itemTitle=_itemTitle - In the implementation block
@property (nonatomic,copy) NSString * providerName;                //@synthesize providerName=_providerName - In the implementation block
@property (nonatomic,copy) NSString * searchTerm;                  //@synthesize searchTerm=_searchTerm - In the implementation block
-(NSString *)searchTerm;
-(void)setSearchTerm:(NSString *)arg1 ;
-(void)setItemIdentifier:(NSNumber *)arg1 ;
-(NSURL *)URL;
-(NSString *)itemTitle;
-(void)setContentKind:(int)arg1 ;
-(NSString *)providerName;
-(NSNumber *)itemIdentifier;
-(NSString *)categoryName;
-(void)setCategoryName:(NSString *)arg1 ;
-(int)targetApplication;
-(int)contentKind;
-(int)_targetApplicationWithContentKind:(int)arg1 ;
-(id)_URLSchemeWithApplication:(int)arg1 ;
-(id)_stringForContentKind:(int)arg1 ;
-(void)setItemTitle:(NSString *)arg1 ;
-(void)setProviderName:(NSString *)arg1 ;
-(void)setTargetApplication:(int)arg1 ;
@end

