/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:57 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, SSXPCConnection, NSHashTable, NSArray, NSMutableArray;

@interface SSVDirectUploadQueue : NSObject {

	NSObject*<OS_dispatch_queue> _accessQueue;
	int _daemonLaunchToken;
	SSXPCConnection* _inboundConnection;
	NSObject*<OS_dispatch_queue> _observerQueue;
	NSHashTable* _observers;
	SSXPCConnection* _outboundConnection;
	NSArray* _uploadKinds;
	NSMutableArray* _uploads;

}

@property (copy,readonly) NSArray * uploadKinds; 
-(void)dealloc;
-(id)init;
-(id)initWithUploadKinds:(id)arg1 ;
-(void)addUploadObserver:(id)arg1 ;
-(void)removeUploadObserver:(id)arg1 ;
-(void)getUploadsWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)cancelUploads:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)pauseUploads:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)resumeUploads:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)_establishInboundConnection;
-(void)_sendSimpleMessage:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)_outboundConnection;
-(void)_handleInboundMessage:(id)arg1 connection:(id)arg2 ;
-(void)_sendObserversUploadsDidChange;
-(void)_handleAddUploadsMessage:(id)arg1 ;
-(void)_handleChangeUploadsMessage:(id)arg1 ;
-(void)_handleRemoveUploadsMessage:(id)arg1 ;
-(void)cancelAllUploadsWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)pauseAllUploadsWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)resumeAllUploadsWithCompletionBlock:(/*^block*/id)arg1 ;
-(NSArray *)uploadKinds;
@end

