/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:15 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PreferenceBundles/VictoriaSettings.bundle/VictoriaSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPMediaPickerControllerDelegate <NSObject>
@optional
-(void)mediaPicker:(id)arg1 didPickMediaItems:(id)arg2;
-(void)mediaPickerDidCancel:(id)arg1;

@end

