/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:15 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PreferenceBundles/VictoriaSettings.bundle/VictoriaSettings
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSViewController.h>
#import <VictoriaSettings/STEmpedLinkingManagerDelegate.h>
#import <VictoriaSettings/STLinkingViewDelegate.h>

@class STLinkingView, UILabel, STEmpedLinkingManager, NSString;

@interface NikeSettingsLinkingController : PSViewController <STEmpedLinkingManagerDelegate, STLinkingViewDelegate> {

	STLinkingView* _linkingView;
	UILabel* _titleLabel;
	STEmpedLinkingManager* _linkingManager;
	char _isRemoteLinking;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id)init;
-(void)suspend;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(id)bundle;
-(void)_configureLinkingAnimated:(char)arg1 ;
-(void)_setTitleLabelText:(id)arg1 ;
-(void)_updateForSensorStatusChange;
-(void)linkingViewRequestsEmpedSearch:(id)arg1 ;
-(void)linkingViewRequestsRemoteSearch:(id)arg1 ;
-(void)linkingViewRequestsPop:(id)arg1 ;
-(void)empedLinkingManager:(id)arg1 linkedStateChanged:(char)arg2 ;
-(void)empedLinkingManager:(id)arg1 remoteLinkedStateChanged:(char)arg2 ;
@end

