/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:46 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class CTTelephonyNetworkInfo, NSString;

@interface CTRadioAccessTechnology : NSObject {

	CTTelephonyNetworkInfo* _networkInfo;

}

@property (readonly) NSString * radioAccessTechnology; 
-(id)initWithCTTelephonyNetworkInfo:(id)arg1 ;
-(NSString *)radioAccessTechnology;
-(void)dealloc;
-(id)init;
@end

