/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:56 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/StoreKitUI.axbundle/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/StoreKitUI-Structs.h>
#import <StoreKitUI/__SKUICardViewElementCollectionViewCellAccessibility_super.h>

@interface SKUICardViewElementCollectionViewCellAccessibility : __SKUICardViewElementCollectionViewCellAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(id)_accessibilityFindPlayButton;
-(id)_axLockupElement;
-(id)_axAdornedImageElement;
-(id)_accessibilityHitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(id)_accessibilitySupplementaryFooterViews;
-(id)accessibilityLabel;
-(CGPoint)accessibilityActivationPoint;
-(unsigned long long)accessibilityTraits;
-(char)isAccessibilityElement;
-(char)accessibilityActivate;
-(id)accessibilityCustomActions;
@end

