/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:56 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/StoreKitUI.axbundle/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/__SKUISegmentedTableHeaderViewAccessibility_super.h>

@interface SKUISegmentedTableHeaderViewAccessibility : __SKUISegmentedTableHeaderViewAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(int)_accessibilitySortPriority;
-(char)shouldGroupAccessibilityChildren;
-(void)setSegmentedControl:(id)arg1 ;
@end

