/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:20 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayerUI/MediaPlayerUI-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@class UILabel;

@interface _MPUExtrasMainMenuItemCollectionViewCell : UICollectionViewCell {

	UILabel* _textLabel;

}

@property (nonatomic,readonly) UILabel * textLabel;              //@synthesize textLabel=_textLabel - In the implementation block
+(id)_createLabelInCell:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setSelected:(char)arg1 ;
-(UILabel *)textLabel;
-(void)_dynamicTypeChanged;
@end

