/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:19 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayerUI/MediaPlayerUI-Structs.h>
#import <UIKit/UIView.h>

@interface MPUIndeterminateProgressIndicatorView : UIView {

	float _progressLineWidth;
	float _progressGap;

}

@property (assign,nonatomic) float progressLineWidth;              //@synthesize progressLineWidth=_progressLineWidth - In the implementation block
@property (assign,nonatomic) float progressGap;                    //@synthesize progressGap=_progressGap - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(void)tintColorDidChange;
-(void)didMoveToSuperview;
-(void)_willEnterForeground:(id)arg1 ;
-(void)setProgressGap:(float)arg1 ;
-(void)_updateAnimation;
-(float)progressLineWidth;
-(float)progressGap;
-(void)setProgressLineWidth:(float)arg1 ;
@end

