/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:20 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ABDateFieldDelegate
@required
-(char)dateFieldShouldClear:(id)arg1;
-(void)dateFieldDateDidChange:(id)arg1;
-(char)dateFieldShouldBeginEditing:(id)arg1;
-(void)dateFieldDidBeginEditing:(id)arg1;
-(char)dateFieldShouldEndEditing:(id)arg1;
-(void)dateFieldDidEndEditing:(id)arg1;

@end

