/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:26 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AddressBookUI/AddressBookUI-Structs.h>
#import <AddressBookUI/ABPickerViewController.h>

@class TKVibrationPickerViewController, UIBarButtonItem;

@interface ABVibrationPickerViewController : ABPickerViewController {

	TKVibrationPickerViewController* _vibrationPickerViewController;
	char _canEnterEditingMode;
	UIBarButtonItem* _saveButton;

}

@property (nonatomic,retain,readonly) TKVibrationPickerViewController * vibrationPickerViewController; 
@property (setter=_setSaveButton:,nonatomic,retain) UIBarButtonItem * _saveButton;                                  //@synthesize saveButton=_saveButton - In the implementation block
-(float)ab_heightToFitForViewInPopoverView;
-(id)initWithAlertType:(int)arg1 ;
-(TKVibrationPickerViewController *)vibrationPickerViewController;
-(void)_vibrationSaveButtonClicked:(id)arg1 ;
-(void)_setSaveButton:(id)arg1 ;
-(UIBarButtonItem *)_saveButton;
-(void)setStyleProvider:(id)arg1 ;
-(void)dealloc;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(void)loadView;
-(void)_getRotationContentSettings:(SCD_Struct_AB0*)arg1 ;
@end

