/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:06 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CNFUIUtilities : NSObject
+(id)formattedPhoneNumberFromString:(id)arg1 ;
+(id)callDurationStringForChat:(id)arg1 ;
+(id)statusStringForState:(unsigned)arg1 ;
+(id)currentCallDurationString;
@end

