/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:35:54 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/AccessibilityBundles/MediaPlayerUIFramework.axbundle/MediaPlayerUIFramework
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayerUIFramework/__MPUNowPlayingViewControllerAccessibility_super.h>

@interface MPUNowPlayingViewControllerAccessibility : __MPUNowPlayingViewControllerAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryTargetClass;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(void)_axAnnotateAlbumArtAndLyrics;
-(void)_accessibilityLoadAccessibilityInformation;
-(void)viewDidLoad;
-(void)_tapAction:(id)arg1 ;
-(id)_createContentViewForItem:(id)arg1 contentViewController:(id*)arg2 ;
-(void)_updateForCurrentItemAnimated:(char)arg1 ;
@end

