/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:06 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/WatchKit.framework/WatchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSData, SPAssetCacheSyncData;

@interface SPCacheMessage : NSObject {

	long _messageType;
	unsigned _cacheType;
	NSString* _assetKey;
	NSString* _gizmoCacheIdentifier;
	NSData* _assetData;
	SPAssetCacheSyncData* _syncData;
	unsigned _error;

}

@property (assign,nonatomic) long messageType;                             //@synthesize messageType=_messageType - In the implementation block
@property (assign,nonatomic) unsigned cacheType;                           //@synthesize cacheType=_cacheType - In the implementation block
@property (nonatomic,retain) NSString * assetKey;                          //@synthesize assetKey=_assetKey - In the implementation block
@property (nonatomic,retain) NSString * gizmoCacheIdentifier;              //@synthesize gizmoCacheIdentifier=_gizmoCacheIdentifier - In the implementation block
@property (nonatomic,retain) NSData * assetData;                           //@synthesize assetData=_assetData - In the implementation block
@property (nonatomic,retain) SPAssetCacheSyncData * syncData;              //@synthesize syncData=_syncData - In the implementation block
@property (assign,nonatomic) unsigned error;                               //@synthesize error=_error - In the implementation block
+(id)toProto:(id)arg1 ;
+(id)fromProto:(id)arg1 ;
-(long)messageType;
-(void)setMessageType:(long)arg1 ;
-(id)init;
-(id)initWithDictionary:(id)arg1 ;
-(void)setGizmoCacheIdentifier:(NSString *)arg1 ;
-(unsigned)cacheType;
-(void)setCacheType:(unsigned)arg1 ;
-(NSString *)gizmoCacheIdentifier;
-(unsigned)error;
-(void)setAssetKey:(NSString *)arg1 ;
-(NSString *)assetKey;
-(void)setError:(unsigned)arg1 ;
-(void)setAssetData:(NSData *)arg1 ;
-(NSData *)assetData;
-(SPAssetCacheSyncData *)syncData;
-(void)setSyncData:(SPAssetCacheSyncData *)arg1 ;
@end

