/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:35 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface SWRunWorkoutProxy : NSObject

@property (nonatomic,readonly) NSString * goalType; 
@property (nonatomic,readonly) NSString * presetGoal; 
@property (nonatomic,readonly) float goal; 
@property (nonatomic,readonly) NSString * sensorSearchState; 
@property (nonatomic,readonly) NSString * workoutState; 
@property (nonatomic,readonly) NSDictionary * workoutData; 
@property (nonatomic,readonly) char hasEverStarted; 
@property (nonatomic,readonly) char hasPowerSong; 
@property (nonatomic,readonly) NSString * powerSongName; 
@property (nonatomic,readonly) char shouldControlMusic; 
@property (nonatomic,readonly) int musicSelection; 
@property (nonatomic,readonly) NSString * currentSongName; 
@property (nonatomic,readonly) NSString * currentAlbumName; 
@property (nonatomic,readonly) NSString * currentArtistName; 
+(void)initialize;
+(id)newProxy;
-(void)beginSeekingForward;
-(void)beginSeekingBackward;
-(void)endSeeking;
-(void)activateWorkout;
-(void)pauseWorkout;
-(void)selectNextSong;
-(void)selectPreviousSong;
-(void)playOnDemandPrompt;
-(void)endWorkout;
-(void)prepareToActivateWorkout;
-(void)playPowerSong;
-(void)goToNowPlaying;
-(void)pauseMusic;
-(void)playMusic;
@end

