/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:42:21 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSString, NSArray;

@interface SAUIAddViews : SABaseClientBoundCommand

@property (nonatomic,copy) NSString * dialogPhase; 
@property (nonatomic,copy) NSString * displayTarget; 
@property (assign,nonatomic) char scrollToTop; 
@property (assign,nonatomic) char temporary; 
@property (nonatomic,copy) NSArray * views; 
+(id)addViews;
+(id)addViewsWithDictionary:(id)arg1 context:(id)arg2 ;
-(id)afui_dialogPhase;
-(char)_afui_isUsefulUserResultCommand;
-(id)groupIdentifier;
-(char)scrollToTop;
-(id)encodedClassName;
-(char)requiresResponse;
-(NSString *)dialogPhase;
-(void)setDialogPhase:(NSString *)arg1 ;
-(NSString *)displayTarget;
-(void)setDisplayTarget:(NSString *)arg1 ;
-(void)setScrollToTop:(char)arg1 ;
-(char)temporary;
-(void)setTemporary:(char)arg1 ;
-(void)setViews:(NSArray *)arg1 ;
-(NSArray *)views;
@end

