/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:58 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/Social.framework/Social
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SLService : NSObject
+(id)allServices;
+(id)serviceForServiceType:(id)arg1 ;
-(void)addExtraParameters:(id)arg1 forRequest:(id)arg2 ;
-(char)isFirstClassService;
-(int)maximumURLCount;
-(int)maximumImageCount;
-(int)maximumImageDataSize;
-(int)maximumVideoCount;
-(int)maximumVideoDataSize;
-(int)maximumVideoTimeLimit;
-(char)supportsImageURL:(id)arg1 ;
-(char)supportsVideoURL:(id)arg1 ;
-(id)composeViewController;
-(id)activityTitle;
-(id)activityImage;
-(id)accountType;
-(id)serviceType;
-(char)hasAccounts;
@end

