/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:41 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class LSApplicationWorkspace;

@interface GKApplicationWorkspace : NSObject {

	LSApplicationWorkspace* _lsWorkspace;

}

@property (nonatomic,retain) LSApplicationWorkspace * lsWorkspace;              //@synthesize lsWorkspace=_lsWorkspace - In the implementation block
+(id)defaultWorkspace;
-(void)dealloc;
-(char)applicationIsInstalled:(id)arg1 ;
-(void)openSettings;
-(void)setLsWorkspace:(LSApplicationWorkspace *)arg1 ;
-(id)applicationProxyForBundleID:(id)arg1 ;
-(void)openICloudSettings;
-(LSApplicationWorkspace *)lsWorkspace;
-(id)initWithWorkspace:(id)arg1 ;
@end

