/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:41 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface GKCachePair : NSObject {

	id _value;
	id _key;

}

@property (nonatomic,retain) id value;              //@synthesize value=_value - In the implementation block
@property (nonatomic,retain) id key;                //@synthesize key=_key - In the implementation block
-(void)dealloc;
-(id)key;
-(id)value;
-(void)setValue:(id)arg1 ;
-(void)setKey:(id)arg1 ;
@end

