/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:37 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreFoundation/CoreFoundation-Structs.h>
#import <CoreFoundation/NSData.h>

@interface NSMutableData : NSData

@property (readonly) void* mutableBytes; 
@property (assign) unsigned length; 
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)dataWithLength:(unsigned)arg1 ;
+(id)dataWithCapacity:(unsigned)arg1 ;
-(void)abAppendString:(id)arg1 ;
-(void)mf_convertNetworkLineEndingsToUnixInRange:(NSRange)arg1 ;
-(void)mf_makeImmutable;
-(void)mf_appendCString:(const char*)arg1 ;
-(void)mf_convertNetworkLineEndingsToUnix;
-(void)mf_appendRFC2231CompliantValue:(id)arg1 forKey:(id)arg2 ;
-(char)_isCompact;
-(void)resetBytesInRange:(NSRange)arg1 ;
-(void)replaceBytesInRange:(NSRange)arg1 withBytes:(const void*)arg2 ;
-(id)initWithCapacity:(unsigned)arg1 ;
-(void)appendBytes:(const void*)arg1 length:(unsigned)arg2 ;
-(Class)classForCoder;
-(void)setData:(id)arg1 ;
-(void)setLength:(unsigned)arg1 ;
-(void)appendData:(id)arg1 ;
-(void*)mutableBytes;
-(id)initWithLength:(unsigned)arg1 ;
-(void)replaceBytesInRange:(NSRange)arg1 withBytes:(const void*)arg2 length:(unsigned)arg3 ;
-(void)increaseLengthBy:(unsigned)arg1 ;
@end

