/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:31 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	char field1;
	char field2;
	char field3;
	char field4;
} SCD_Struct_Bl2;

typedef struct BTLocalDeviceImpl* BTLocalDeviceImplRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDiscoveryAgentImpl* BTDiscoveryAgentImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct BTAccessoryManagerImpl* BTAccessoryManagerImplRef;

