/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:51 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PKPaymentWebServiceResponse : NSObject {

	id _JSONObject;

}

@property (nonatomic,readonly) id JSONObject;              //@synthesize JSONObject=_JSONObject - In the implementation block
+(id)responseWithData:(id)arg1 ;
-(void)dealloc;
-(id)initWithData:(id)arg1 ;
-(id)JSONObject;
@end

