/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:14 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <libAVFAudio.dylib/libAVFAudio.dylib-Structs.h>
@class AVAudioOutputNode, AVAudioInputNode, AVAudioMixerNode;

@interface AVAudioEngine : NSObject {

	void* _impl;

}

@property (assign,nonatomic) OpaqueMusicSequenceRef musicSequence; 
@property (nonatomic,readonly) AVAudioOutputNode * outputNode; 
@property (nonatomic,readonly) AVAudioInputNode * inputNode; 
@property (nonatomic,readonly) AVAudioMixerNode * mainMixerNode; 
@property (getter=isRunning,nonatomic,readonly) char running; 
-(void)attachNode:(id)arg1 ;
-(void)detachNode:(id)arg1 ;
-(AVAudioOutputNode *)outputNode;
-(AVAudioInputNode *)inputNode;
-(AVAudioMixerNode *)mainMixerNode;
-(void)connect:(id)arg1 to:(id)arg2 fromBus:(unsigned)arg3 toBus:(unsigned)arg4 format:(id)arg5 ;
-(void)connect:(id)arg1 to:(id)arg2 format:(id)arg3 ;
-(void)disconnectNodeInput:(id)arg1 bus:(unsigned)arg2 ;
-(void)disconnectNodeOutput:(id)arg1 bus:(unsigned)arg2 ;
-(void)disconnectNodeInput:(id)arg1 ;
-(void)disconnectNodeOutput:(id)arg1 ;
-(char)startAndReturnError:(id*)arg1 ;
-(void)setMusicSequence:(OpaqueMusicSequenceRef)arg1 ;
-(OpaqueMusicSequenceRef)musicSequence;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)reset;
-(void)stop;
-(char)isRunning;
-(void)pause;
-(AVAudioEngineImpl*)implementation;
-(void)prepare;
@end

