/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:14 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAVFAudio.dylib/NSSecureCoding.h>

@class NSString;

@interface AVSpeechSynthesisVoice : NSObject <NSSecureCoding>

@property (nonatomic,copy) NSString * language; 
+(id)currentLanguageCode;
+(id)voiceWithLanguage:(id)arg1 ;
+(id)speechVoices;
+(void)initialize;
+(char)supportsSecureCoding;
+(id)currentLanguageCode;
+(id)voiceWithLanguage:(id)arg1 ;
+(id)speechVoices;
-(id)initWithLanguage:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)description;
-(NSString *)language;
-(void)setLanguage:(NSString *)arg1 ;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

