/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:12 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class AVVideoPerformanceMetricsInternal;

@interface AVVideoPerformanceMetrics : NSObject {

	AVVideoPerformanceMetricsInternal* _performanceMetricsInternal;

}

@property (nonatomic,readonly) unsigned long totalNumberOfVideoFrames; 
@property (nonatomic,readonly) unsigned long numberOfDroppedVideoFrames; 
@property (nonatomic,readonly) unsigned long numberOfCorruptedVideoFrames; 
@property (nonatomic,readonly) double totalFrameDelay; 
-(unsigned long)totalNumberOfVideoFrames;
-(unsigned long)numberOfCorruptedVideoFrames;
-(double)totalFrameDelay;
-(unsigned long)numberOfDroppedVideoFrames;
-(void)dealloc;
-(id)init;
-(id)initWithDictionary:(id)arg1 ;
-(void)finalize;
@end

