/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:25 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <YouTube/YTXMLHTTPRequest.h>

@class NSMutableArray;

@interface YTCategoriesRequest : YTXMLHTTPRequest {

	id _delegate;
	NSMutableArray* _categories;
	char _responseIndicatesAuthenticationFailure;

}
-(void)failWithError:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)clearDelegate;
-(void)loadRequest:(id)arg1 ;
-(int)parseData:(id)arg1 ;
-(char)receivedValidResponse:(id)arg1 ;
-(void)didParseData;
-(void)didAuthenticate:(id)arg1 ;
-(id)_categoriesURL;
-(void)requestCategoriesWithDelegate:(id)arg1 ;
@end

