/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:59 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableSet, CKRecord;

@interface CKRecordGraphNode : NSObject {

	NSMutableSet* _edges;
	int _indegree;
	CKRecord* _record;

}

@property (nonatomic,copy) NSMutableSet * edges;              //@synthesize edges=_edges - In the implementation block
@property (assign,nonatomic) int indegree;                    //@synthesize indegree=_indegree - In the implementation block
@property (nonatomic,retain) CKRecord * record;               //@synthesize record=_record - In the implementation block
-(id)init;
-(id)description;
-(void)setEdges:(NSMutableSet *)arg1 ;
-(NSMutableSet *)edges;
-(CKRecord *)record;
-(void)setRecord:(CKRecord *)arg1 ;
-(id)CKPropertiesDescription;
-(int)indegree;
-(void)setIndegree:(int)arg1 ;
@end

