/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:16 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface MPUBlockAnimationDelegate : NSObject {

	/*^block*/id _completionHandler;

}

@property (nonatomic,copy,readonly) id completionHandler;              //@synthesize completionHandler=_completionHandler - In the implementation block
-(void)animationDidStop:(id)arg1 finished:(char)arg2 ;
-(id)initWithCompletionHandler:(/*^block*/id)arg1 ;
-(id)completionHandler;
@end

