/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:03 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface TIKeyboardKeyBehaviors : NSObject {

	unsigned _spaceKeyBehavior;
	unsigned _returnKeyBehavior;

}

@property (assign,nonatomic) unsigned spaceKeyBehavior;               //@synthesize spaceKeyBehavior=_spaceKeyBehavior - In the implementation block
@property (assign,nonatomic) unsigned returnKeyBehavior;              //@synthesize returnKeyBehavior=_returnKeyBehavior - In the implementation block
+(id)behaviorForSpaceKey:(unsigned)arg1 forReturnKey:(unsigned)arg2 ;
-(unsigned)spaceKeyBehavior;
-(unsigned)returnKeyBehavior;
-(id)initWithSpaceKeyBehavior:(unsigned)arg1 returnKeyBehavior:(unsigned)arg2 ;
-(void)setSpaceKeyBehavior:(unsigned)arg1 ;
-(void)setReturnKeyBehavior:(unsigned)arg1 ;
@end

