/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface _CKDispatchQueueBlock : NSObject {

	/*^block*/id _block;
	NSString* _key;
	int _priority;
	unsigned _fifo;

}

@property (nonatomic,copy) id block;                     //@synthesize block=_block - In the implementation block
@property (nonatomic,copy) NSString * key;               //@synthesize key=_key - In the implementation block
@property (assign,nonatomic) int priority;               //@synthesize priority=_priority - In the implementation block
@property (assign,nonatomic) unsigned fifo;              //@synthesize fifo=_fifo - In the implementation block
-(void)cancel;
-(void)dealloc;
-(id)description;
-(NSString *)key;
-(int)compare:(id)arg1 ;
-(void)setPriority:(int)arg1 ;
-(void)setKey:(NSString *)arg1 ;
-(int)priority;
-(id)initWithBlock:(/*^block*/id)arg1 key:(id)arg2 priority:(int)arg3 fifo:(unsigned)arg4 ;
-(unsigned)fifo;
-(void)setFIFO:(unsigned)arg1 ;
-(id)block;
-(void)setBlock:(id)arg1 ;
@end

