/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:50 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <ChatKit/ChatKit-Structs.h>
@interface CKAttachmentItemManager : NSObject
+(id)attachmentWithFileURL:(id)arg1 size:(CGSize)arg2 guid:(id)arg3 ;
@end

