/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:48 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ChatKit/ChatKit-Structs.h>
#import <ChatKit/CKMediaObject.h>

@class CKImageData, UIImage;

@interface CKImageMediaObject : CKMediaObject {

	CKImageData* _imageData;
	CKImageData* _backgroundImageData;
	UIImage* _thumbnail;

}

@property (nonatomic,retain,readonly) CKImageData * imageData; 
@property (nonatomic,retain) UIImage * thumbnail;                           //@synthesize thumbnail=_thumbnail - In the implementation block
+(id)UTITypes;
+(id)fallbackFilenamePrefix;
+(id)attachmentSummary:(unsigned)arg1 ;
+(Class)imageDataClass;
+(char)isPreviewable;
+(Class)__ck_attachmentItemClass;
-(void)dealloc;
-(id)location;
-(UIImage *)thumbnail;
-(void)setThumbnail:(UIImage *)arg1 ;
-(void)export:(id)arg1 ;
-(char)canExport;
-(id)generateThumbnailFillToSize:(CGSize)arg1 contentAlignmentInsets:(UIEdgeInsets)arg2 ;
-(CGSize)bbSize;
-(id)generateThumbnailForWidth:(float)arg1 orientation:(char)arg2 ;
-(CKImageData *)imageData;
-(int)mediaType;
@end

