/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:46 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CKJoystickControllerDelegate <NSObject>
@optional
-(void)joystickControllerWillPresentJoystick:(id)arg1 animated:(char)arg2;
-(void)joystickControllerWillDismissJoystick:(id)arg1 animated:(char)arg2;
-(void)joystickControllerWillExpandJoystick:(id)arg1 animated:(char)arg2;
-(void)joystickControllerWillShrinkJoystick:(id)arg1 animated:(char)arg2;
-(void)joystickControllerDidPresentJoystick:(id)arg1;
-(void)joystickControllerDidDismissJoystick:(id)arg1;
-(void)joystickControllerDidExpandJoystick:(id)arg1;
-(void)joystickControllerDidShrinkJoystick:(id)arg1;

@end

