/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:52 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CKRecipientSelectionControllerDelegate <NSObject>
@required
-(void)recipientSelectionController:(id)arg1 textDidChange:(id)arg2;
-(void)recipientSelectionControllerReturnPressed:(id)arg1;
-(void)recipientSelectionControllerDidChangeSize:(id)arg1;
-(void)recipientSelectionControllerDidPushABViewController:(id)arg1;
-(void)recipientSelectionControllerRequestDismissKeyboard:(id)arg1;
-(void)recipientSelectionController:(id)arg1 didFinishAvailaiblityLookupForRecipient:(id)arg2;
-(void)recipientSelectionControllerSearchListDidShowOrHide:(id)arg1;
-(UIEdgeInsets*)navigationBarInsetsForRecipientSelectionController:(id)arg1;

@end

