/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:40:05 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CommunicationsSetupUI/CNFRegAppearanceController.h>

@interface CNFRegModernAppearanceController : CNFRegAppearanceController
-(int)modalPresentationStyle;
-(id)tableBackgroundColor;
-(char)styleUsesCustomTableStyle;
-(id)tableCellCheckmarkImageDisabled;
-(id)tableCellTextLabelBackgroundColor;
-(id)tableCellTextLabelColor;
-(id)tableCellDetailLabelColor;
-(id)tableCellDetailLabelBackgroundColor;
-(id)tableHeaderTextColor;
-(id)tableFooterTextColor;
-(id)tableCellCheckmarkImage;
-(id)tableHeaderFont;
-(id)tableFooterFont;
-(int)tableHeaderTextAlignment;
-(int)tableFooterTextAlignment;
-(id)webViewBackgroundView;
-(id)webViewBackgroundColor;
-(char)webViewIsOpaque;
-(char)webViewDrawsShadows;
-(char)firstNavigationBarHidden;
-(char)navigationBarHidesTitle;
-(char)navigationBarHidesShadow;
@end

