/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:39:21 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface AXReplayer : NSObject
+(id)replayer;
-(void)replayWithName:(id)arg1 attempts:(int)arg2 interval:(double)arg3 async:(char)arg4 queue:(id)arg5 replayBlock:(/*^block*/id)arg6 completion:(/*^block*/id)arg7 ;
@end

