/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:36:49 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/EventKit.framework/EventKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <EventKit/EKCalendarNotification.h>

@interface EKCalendarInviteReplyNotification : EKCalendarNotification {

	int _status;
	unsigned _allowedEntityTypes;

}

@property (assign,nonatomic) int status;                               //@synthesize status=_status - In the implementation block
@property (assign,nonatomic) unsigned allowedEntityTypes;              //@synthesize allowedEntityTypes=_allowedEntityTypes - In the implementation block
-(unsigned)allowedEntityTypes;
-(id)inviteReplyNotificationFromEventStore:(id)arg1 ;
-(void)setAllowedEntityTypes:(unsigned)arg1 ;
-(id)initWithType:(int)arg1 ;
-(int)status;
-(void)setStatus:(int)arg1 ;
@end

