/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:34 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/SearchBundles/VoiceMemos.searchBundle/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <VoiceMemos/SPSearchResult.h>

@class NSString, NSDate, NSURL;

@interface VMSearchResult : NSObject <SPSearchResult> {

	NSString* _title;
	NSDate* _modDate;
	double _duration;
	NSURL* _url;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(unsigned long long)identifier;
-(int)domain;
-(const char*)titleUTF8String;
-(const char*)auxiliaryTitleUTF8String;
-(const char*)summaryUTF8String;
-(const char*)URLUTF8String;
-(id)initWithVoiceMemo:(id)arg1 ;
@end

